import {useEffect,useRef,useState,type FormEvent} from 'react';
import {GameSelect,GameSelectOption} from '../components/ui/game-select';

type Item={id:number;name:string;count:number;icon?:string};
type Gift={id:string;name:string;description:string;copper:number;items:Item[]};
type Buff={id:string;name:string;description:string;scope:string;userId?:string;effects:Record<string,number>;endsWall:number;revoked:boolean};
const fields:[string,string,number,number][]=[['xpMultiplier','经验倍率',1,10],['movementMultiplier','移动速度倍率',1,3],['maxHp','生命上限',0,100000],['maxMana','法力上限',0,100000],['armor','护甲',0,100000],['attackPower','近战攻击强度',0,10000],['rangedAttackPower','远程攻击强度',0,10000],['spellPower','法术强度',0,10000],['healing','治疗强度',0,10000]];
const initialEffects=Object.fromEntries(fields.map(([key,,min])=>[key,min]));
async function request(path:string,body?:unknown){const response=await fetch('/api/admin/'+path,body?{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)}:undefined);const data=await response.json();if(!response.ok)throw new Error(data.error||'请求失败');return data;}
export default function AdminRewards(){
 const [templates,setTemplates]=useState<Gift[]>([]),[buffs,setBuffs]=useState<Buff[]>([]),[operations,setOperations]=useState<{id:string;action:string;reason:string;createdAt:number;result:{recipients?:number;name?:string}}[]>([]);
 const [mountItems,setMountItems]=useState<Item[]>([]);
 const [serverNow,setServerNow]=useState(0);
 const [busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[loaded,setLoaded]=useState(false);
 const [tab,setTab]=useState<'gift'|'buff'>('gift'),[templateId,setTemplateId]=useState(''),[name,setName]=useState(''),[description,setDescription]=useState(''),[gold,setGold]=useState('0'),[items,setItems]=useState<Item[]>([]);
 const [search,setSearch]=useState(''),[results,setResults]=useState<Item[]>([]),[scope,setScope]=useState('all'),[userId,setUserId]=useState(''),[playerSearch,setPlayerSearch]=useState(''),[players,setPlayers]=useState<{id:string;username:string}[]>([]);
 const [selectedGift,setSelectedGift]=useState(''),[reason,setReason]=useState(''),[buffName,setBuffName]=useState(''),[buffDescription,setBuffDescription]=useState(''),[minutes,setMinutes]=useState(60),[effects,setEffects]=useState(initialEffects);
 const [pending,setPending]=useState<{body:Record<string,unknown>;summary:string}|null>(null);const dialog=useRef<HTMLDialogElement>(null);
 const refresh=async()=>{const data=await request('gm');setTemplates(data.templates);setMountItems(data.mounts);setBuffs(data.buffs);setOperations(data.operations);setServerNow(data.serverNow);setLoaded(true);};
 useEffect(()=>{let active=true;request('gm').then(data=>{if(active){setTemplates(data.templates);setMountItems(data.mounts);setBuffs(data.buffs);setOperations(data.operations);setServerNow(data.serverNow);setLoaded(true);}}).catch(e=>{if(active)setError(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{if(pending)dialog.current?.showModal();else dialog.current?.close();},[pending]);
 async function run(body:Record<string,unknown>){
  setBusy(true);setError('');setNotice('');
  try{const result=await request('gm',body);setPending(null);setNotice(body.action==='saveGift'?'礼包配置已保存。':body.action==='sendGift'?`已发放到 ${result.recipients} 个存档，等待玩家领取。`:body.action==='issueBuff'?'Buff 已发布，在线本地战斗会在下次同步时生效。':'Buff 已撤销。');if(body.action==='saveGift'){setTemplateId(result.id);setSelectedGift(result.id);}await refresh();}
  catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const confirm=(body:Record<string,unknown>,summary:string)=>{setError('');setPending({body:{...body,reason,requestId:crypto.randomUUID()},summary});};
 const edit=(gift:Gift)=>{setTemplateId(gift.id);setName(gift.name);setDescription(gift.description);setGold(String(gift.copper/10000));setItems(gift.items);};
 const target=scope==='all'?'全服':players.find(p=>p.id===userId)?.username||userId;
 return <div className="gm-rewards">
  <div className="gm-actions"><button aria-pressed={tab==='gift'} onClick={()=>setTab('gift')}>礼包配置与发放</button><button aria-pressed={tab==='buff'} onClick={()=>setTab('buff')}>全服 / 定向 Buff</button><button disabled={busy} onClick={()=>{setError('');void refresh().catch(e=>setError(e.message));}}>刷新列表</button></div>
  {error&&<p role="alert" className="gm-error">{error}</p>}{notice&&<p role="status" className="gm-notice">{notice}</p>}{!loaded&&!error&&<p role="status">正在加载发放中心…</p>}
  <section className="gm-panel gm-reward-config"><h2>发放对象</h2><div className="gm-form-grid"><label>范围<GameSelect aria-label="发放范围" value={scope} onValueChange={value=>{setScope(value);setUserId('');}}><GameSelectOption value="all">全服</GameSelectOption><GameSelectOption value="player">指定玩家</GameSelectOption></GameSelect></label>
   {scope==='player'&&<><form className="gm-inline-search" onSubmit={async event=>{event.preventDefault();setError('');try{const data=await request(`players?search=${encodeURIComponent(playerSearch)}`);setPlayers(data.rows);if(!data.rows.length)setError('没有找到玩家。');}catch(e){setError((e as Error).message);}}}><label>搜索玩家<input required value={playerSearch} maxLength={100} onChange={e=>setPlayerSearch(e.target.value)} placeholder="用户名或账号 ID"/></label><button>搜索</button></form><label>目标玩家<GameSelect value={userId} onValueChange={setUserId} aria-label="目标玩家"><GameSelectOption value="">请选择玩家</GameSelectOption>{players.map(p=><GameSelectOption key={p.id} value={p.id}>{p.username}</GameSelectOption>)}</GameSelect></label></>}
   <label>操作原因<input required value={reason} maxLength={500} onChange={e=>setReason(e.target.value)} placeholder="例如：节日福利 / 问题补偿"/></label></div>
   <p className="gm-muted">礼包按发放时的现有存档逐份投递；每个存档只能领取一次。指定玩家会覆盖其所有现有存档。Buff 在有效期内也覆盖其新建角色，不受地图或阵营限制。</p>
  </section>
  {tab==='gift'?<div className="gm-reward-columns"><form className="gm-panel gm-reward-config" onSubmit={(event:FormEvent)=>{event.preventDefault();const amount=Number(gold)*10000;if(!Number.isFinite(amount)||Math.abs(amount-Math.round(amount))>0.00001){setError('金币最多填写四位小数（1 铜币）。');return;}confirm({action:'saveGift',...(templateId?{templateId}:{}),name,description,copper:Math.round(amount),items:items.map(({id,count})=>({id,count}))},`保存礼包「${name}」，包含 ${items.length} 种物品和 ${gold} 金。`);}}>
   <header><h2>{templateId?'编辑礼包':'创建礼包'}</h2><button type="button" onClick={()=>{setTemplateId('');setName('');setDescription('');setGold('0');setItems([]);}}>新建</button></header>
   <label>礼包名称<input required maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><label>玩家可见说明<textarea required maxLength={500} rows={2} value={description} onChange={e=>setDescription(e.target.value)}/></label><label>金币（1 金 = 10000 铜）<input required type="number" min={0} max={1000000} step="0.0001" value={gold} onChange={e=>setGold(e.target.value)}/></label>
   <div className="gm-inline-search"><label>添加物品<input value={search} maxLength={100} onChange={e=>setSearch(e.target.value)} placeholder="物品名称或 ID"/></label><button type="button" disabled={!search.trim()} onClick={async()=>{setError('');try{const data=await request(`gm-items?search=${encodeURIComponent(search)}`);setResults(data.items);if(!data.items.length)setError('没有找到物品。');}catch(e){setError((e as Error).message);}}}>查找</button></div>
   <div className="gm-item-results" aria-label="添加坐骑物品">{mountItems.map(item=><button key={item.id} type="button" disabled={items.length>=20||items.some(entry=>entry.id===item.id)} onClick={()=>setItems(old=>[...old,{...item,count:1}])}>{item.icon&&<img src={item.icon} alt=""/>}{item.name} ＋</button>)}</div><p className="gm-muted gm-small">坐骑以物品寄送，领取到背包后使用即可加入收藏；20 级起可骑乘。</p>
   {results.length>0&&<div className="gm-item-results">{results.map(item=><button key={item.id} type="button" disabled={items.length>=20||items.some(entry=>entry.id===item.id)} onClick={()=>setItems(old=>[...old,{...item,count:1}])}>{item.icon&&<img src={item.icon} alt=""/>}{item.name} <small>#{item.id}</small> ＋</button>)}</div>}
   {items.map(item=><div className="gm-gift-item" key={item.id}><span>{item.icon&&<img src={item.icon} alt=""/>}{item.name} <small>#{item.id}</small></span><input aria-label={`${item.name}数量`} required type="number" min={1} max={1000} value={item.count} onChange={e=>setItems(old=>old.map(entry=>entry.id===item.id?{...entry,count:Number(e.target.value)}:entry))}/><button type="button" aria-label={`移除${item.name}`} onClick={()=>setItems(old=>old.filter(entry=>entry.id!==item.id))}>移除</button></div>)}
   <button className="gm-primary" disabled={busy||!reason.trim()||(!items.length&&Number(gold)<=0)}>保存礼包配置</button><p className="gm-muted gm-small">修改模板不会改变已发放的礼包内容。每个礼包最多 20 种物品。</p>
  </form><section className="gm-panel gm-reward-config"><h2>一键发放</h2><label>选择已保存礼包<GameSelect value={selectedGift} onValueChange={setSelectedGift} aria-label="选择礼包"><GameSelectOption value="">请选择礼包</GameSelectOption>{templates.map(gift=><GameSelectOption key={gift.id} value={gift.id}>{gift.name}</GameSelectOption>)}</GameSelect></label>
   {templates.filter(gift=>gift.id===selectedGift).map(gift=><article className="gm-gift-preview" key={gift.id}><h3>{gift.name}</h3><p>{gift.description}</p><ul>{gift.items.map(item=><li key={item.id}>{item.name} × {item.count}</li>)}</ul><strong>{gift.copper/10000} 金</strong></article>)}
   <button className="gm-primary" disabled={busy||!selectedGift||!reason.trim()||scope==='player'&&!userId} onClick={()=>confirm({action:'sendGift',templateId:selectedGift,scope,userId},`将「${templates.find(gift=>gift.id===selectedGift)?.name}」发给${target}的所有现有存档。每次新发放都会生成新礼包。`)}>一键发放礼包</button>
   <h3>已保存礼包</h3>{templates.length===0&&<p className="gm-muted">暂无礼包，请先创建。</p>}{templates.map(gift=><div className="gm-template-row" key={gift.id}><span>{gift.name}<small>{gift.items.length} 种物品 · {gift.copper/10000} 金</small></span><button onClick={()=>edit(gift)}>编辑</button></div>)}
  </section></div>:<><form className="gm-panel gm-reward-config" onSubmit={event=>{event.preventDefault();confirm({action:'issueBuff',scope,userId,name:buffName,description:buffDescription,durationMinutes:minutes,effects},`向${target}发布「${buffName}」，持续 ${minutes} 分钟。不同 Buff 的经验和移动倍率相乘，属性数值相加。`);}}>
   <h2>定制 Buff</h2><div className="gm-form-grid"><label>Buff 名称<input required value={buffName} maxLength={60} onChange={e=>setBuffName(e.target.value)}/></label><label>持续时间（分钟）<input type="number" required min={1} max={43200} value={minutes} onChange={e=>setMinutes(Number(e.target.value))}/></label><label>玩家可见说明<input required value={buffDescription} maxLength={500} onChange={e=>setBuffDescription(e.target.value)}/></label></div><div className="gm-form-grid">{fields.map(([key,label,min,max])=><label key={key}>{label}{key.endsWith('Multiplier')?'（倍率）':'（额外增加）'}<input type="number" required min={min} max={max} step={key.endsWith('Multiplier')?0.1:1} value={effects[key]} onChange={e=>setEffects(old=>({...old,[key]:Number(e.target.value)}))}/></label>)}</div>
   <p className="gm-muted">经验、移动倍率与已有服务器倍率相乘；属性数值相加。持续时间按真实时间计算，离线也会到期。生命/法力加成提高上限，不直接补满。</p><button className="gm-primary" disabled={busy||!reason.trim()||scope==='player'&&!userId}>发布 Buff</button>
  </form><section className="gm-panel gm-reward-config"><h2>Buff 记录</h2>{buffs.length===0&&<p className="gm-muted">暂无 Buff。</p>}{buffs.map(buff=><article className="gm-template-row" key={buff.id}><div><h3>{buff.name} · {buff.scope==='all'?'全服':`玩家 ${buff.userId}`}</h3><p>{buff.description}</p><small>{fields.filter(([key])=>key in buff.effects).map(([key,label])=>`${label} ${buff.effects[key]}`).join(' / ')}</small><p className="gm-muted">{buff.revoked?'已撤销':buff.endsWall<=serverNow?'已到期':`结束于 ${new Date(buff.endsWall).toLocaleString()}`}</p></div><button disabled={busy||buff.revoked||buff.endsWall<=serverNow||!reason.trim()} onClick={()=>confirm({action:'revokeBuff',buffId:buff.id},`提前撤销「${buff.name}」。`)}>撤销</button></article>)}</section></>}
  <section className="gm-panel gm-reward-config"><h2>最近发放记录</h2><p className="gm-muted gm-small">此页展示最近 15 条记录，完整操作可在操作审计中查询。</p>{operations.slice(0,15).map(op=><div className="gm-template-row" key={op.id}><span>{({saveGift:'保存礼包',sendGift:'发放礼包',issueBuff:'发布 Buff',revokeBuff:'撤销 Buff'} as Record<string,string>)[op.action]} · {op.result.name||'礼包配置'}<small>{new Date(op.createdAt).toLocaleString()} · {op.reason}</small></span>{op.result.recipients!==undefined&&<b>{op.result.recipients} 个存档</b>}</div>)}</section>
  <dialog ref={dialog} className="gm-dialog" onCancel={event=>{if(busy)event.preventDefault();else setPending(null);}}><h2>确认管理操作</h2><p>{pending?.summary}</p><p className="gm-muted">原因：{String(pending?.body.reason||'')}</p>{error&&<p className="gm-error" role="alert">{error}</p>}<div className="gm-dialog-actions"><button disabled={busy} onClick={()=>setPending(null)}>取消</button><button className="gm-primary" disabled={busy} onClick={()=>pending&&void run(pending.body)}>{busy?'正在提交…':'确认执行'}</button></div></dialog>
 </div>;
}
