"use client";
import {useState} from 'react';
import {Swords,Shield,Target,Flag,Columns3,ChevronUp,ChevronDown} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {GameSelect,GameSelectOption} from '@/components/ui/game-select';
import {useLocalArena} from '@/lib/local-combat-store';
import ClassIcon from './class-icon';
import ArenaBattle from './arena-battle';
import PvpConfiguration from './pvp-configuration';
import type {GameProps} from './game-ui';
import './arena.css';

const colors:Record<number,string>={1:'#c79c6e',2:'#f58cba',3:'#abd473',4:'#fff569',5:'#e6e4dc',7:'#5c92ea',8:'#69ccf0',9:'#b59ce0',11:'#ff9950'};
const classes:Record<number,string>={1:'战士',2:'圣骑士',3:'猎人',4:'盗贼',5:'牧师',7:'萨满',8:'法师',9:'术士',11:'德鲁伊'};
const roleNames:Record<string,string>={tank:'防护',melee:'近战',ranged:'远程',healer:'治疗'};
const taskNames:Record<string,string>={focus:'集火目标',pressure:'持续压制',protect:'保护队友',control:'控制接力'};
const interruptOptions=[{id:'healer',name:'优先打断治疗者施法'},{id:'focus',name:'只打断当前集火目标'},{id:'any',name:'任何敌方施法（自动分工）'},{id:'off',name:'保留打断，不自动使用'}];
const time=(clock:number)=>{const n=Math.max(0,Math.floor((clock-3000)/1000));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`;};
function Choices({label,value,onChange,rows,disabled=false}:{label:string;value:string;onChange:(v:string)=>void;rows:any[];disabled?:boolean}){
 return <label className="arena-label"><span>{label}</span><GameSelect aria-label={label} value={value} onValueChange={onChange} disabled={disabled}>{rows.map(row=><GameSelectOption value={row.id} key={row.id}>{row.name}</GameSelectOption>)}</GameSelect></label>;
}
function ArenaField({map,teams=[],clock=0,plan,preparing=false,projectiles=[]}:{map:any;teams?:any[];clock?:number;plan?:any;preparing?:boolean;projectiles?:any[]}){
 const width=map.maxX-map.minX,height=map.maxY-map.minY,pad=4;
 const units=teams.flatMap(t=>t.members).map(c=>{const pos=preparing&&plan?.positions?.find((p:any)=>p.id===c.id);return pos?{...c,x:pos.x,y:pos.y}:c;});
 return <div className="arena-field"><svg viewBox={`${map.minX-pad} ${map.minY-pad} ${width+pad*2} ${height+pad*2}`} role="img" aria-label={`${map.name}战场，圆柱阻挡移动和施法视线`}>
  <defs><pattern id="arena-floor" patternUnits="userSpaceOnUse" width="4" height="4"><rect width="4" height="4" fill="#242b2a"/><path d="M4 0H0V4" fill="none" stroke="#363e38" strokeWidth=".07"/></pattern><radialGradient id="arena-pillar"><stop offset="0" stopColor="#9b947b"/><stop offset=".7" stopColor="#756d55"/><stop offset="1" stopColor="#494334"/></radialGradient></defs>
  <rect x={map.minX} y={map.minY} width={width} height={height} rx="1" fill="url(#arena-floor)" stroke="#716448" strokeWidth=".45"/>
  <rect x={map.minX+.4} y={map.minY+.4} width="8" height={height-.8} fill="#518eb019"/><rect x={map.maxX-8.4} y={map.minY+.4} width="8" height={height-.8} fill="#c5675719"/>
  <circle cx="0" cy="0" r="7" fill="none" stroke="#b7a279" strokeWidth=".1" opacity=".4"/>
  <path d={`M0 ${map.minY+2}V${map.maxY-2}`} stroke="#a18a58" strokeWidth=".1" strokeDasharray=".5 1" opacity=".3"/>
  {map.obstacles.map((o:any,i:number)=><g key={i}><circle cx={o.x+.5} cy={o.y+.7} r={o.radius+.3} fill="#0006"/><circle cx={o.x} cy={o.y} r={o.radius} fill="url(#arena-pillar)" stroke="#b1a588" strokeWidth=".15"/><circle cx={o.x} cy={o.y} r={o.radius-.5} fill="none" stroke="#c6bca044" strokeWidth=".1"/></g>)}
  {!preparing&&units.filter(c=>!c.hidden&&c.hp>0&&c.teamId===0).map(c=>{const target=units.find(t=>t.id===c.targetId&&!t.hidden&&t.hp>0);return target?<line key={c.id} x1={c.x} y1={c.y} x2={target.x} y2={target.y} stroke={colors[c.classId]} strokeWidth=".09" strokeDasharray=".5 .7" opacity=".3"/>:null;})}
  {projectiles.map(p=>{const progress=Math.min(1,Math.max(0,(clock-p.startedAt)/Math.max(1,p.landsAt-p.startedAt)));return <circle key={p.id} cx={p.from.x+(p.to.x-p.from.x)*progress} cy={p.from.y+(p.to.y-p.from.y)*progress} r=".25" fill={p.school===4?'#86daff':'#efb969'}/>;})}
  {units.filter(c=>!c.hidden).map((c:any,index:number)=><g key={c.id} className="arena-token" style={{transform:`translate(${c.x}px,${c.y}px)`,opacity:c.hp<=0?.35:1}}><title>{c.name} · {Math.ceil(c.hp)} / {c.maxHp}{c.intent?` · ${c.intent}`:''}</title>
   {c.id===plan?.focusId&&<circle r="1.75" stroke="#ed866c" strokeWidth=".17" fill="none"/>}{c.id===plan?.controlId&&<circle r="1.75" stroke="#b9a1ec" strokeWidth=".16" fill="none" strokeDasharray=".6 .4"/>}
   <circle r={c.petUnit?.65:1.15} fill={colors[c.classId]||'#aaa'} stroke={c.teamId===0?'#8ac8e5':'#ec8876'} strokeWidth=".22"/>
   <text y=".38" textAnchor="middle" fontSize="1.05" fontWeight="bold" fill="#17201d">{c.hp<=0?'×':c.teamId===0?index+1:String.fromCharCode(65+teams[1]?.members.findIndex((u:any)=>u.id===c.id))}</text>
   <rect x="-1.6" y="-2.45" width="3.2" height=".38" fill="#171a19"/><rect x="-1.6" y="-2.45" width={3.2*Math.max(0,c.hp)/Math.max(1,c.maxHp)} height=".38" fill={c.teamId===0?'#7aa985':'#d77967'}/>
   {c.effects?.length>0&&<text textAnchor="middle" y="-3" fontSize=".85" fill="#eee4cb">{c.effects[0].name}</text>}
  </g>)}
  {preparing&&<text x="0" y={map.maxY-1.5} textAnchor="middle" fontSize="1.05" fill="#c5b99a">蓝方出生区 · 立柱同时影响攻击与治疗</text>}
 </svg></div>;
}
function Fighter({unit,clock}: {unit:any;clock:number}){
 const cast=unit.cast,progress=cast?Math.min(100,Math.max(0,(clock-cast.startedAt)/Math.max(1,cast.until-cast.startedAt)*100)):0;
 return <article className={'arena-fighter '+(unit.hp<=0?'is-dead':'')}><div className="arena-fighter-name"><ClassIcon classId={unit.classId} size={25}/><div><strong style={{color:colors[unit.classId]}}>{unit.name}</strong><small>{unit.level}级 {unit.className||classes[unit.classId]} · {roleNames[unit.role]}{unit.hidden?' · 潜行中':''}</small></div></div><div className="arena-health" aria-label={`${unit.name}生命 ${Math.ceil(unit.hp)} / ${unit.maxHp}`}><i style={{width:Math.max(0,unit.hp)/unit.maxHp*100+'%'}}/><span>{Math.ceil(unit.hp)} / {unit.maxHp}</span></div><div className="arena-cast"><i style={{width:progress+'%'}}/>{cast?<span>{cast.name}</span>:<span>{unit.hp<=0?'已倒下':unit.intent||'准备接战'}</span>}</div><div className="arena-effects">{unit.effects?.map((effect:any,i:number)=><span key={i}>{effect.name} {Math.max(0,(effect.until-clock)/1000).toFixed(1)}s</span>)}</div></article>;
}
function Preparation({match,busy,send}:{match:any;busy:boolean;send:GameProps['send']}){
 const [plan,setPlan]=useState(()=>structuredClone(match.plan)),[dirty,setDirty]=useState(false);
 const own=match.teams[0].members,enemy=match.teams[1].members;
 const change=(patch:any)=>{setPlan((p:any)=>({...p,...patch}));setDirty(true);};
 const assignment=(id:string,patch:any)=>change({assignments:plan.assignments.map((a:any)=>a.actorId===id?{...a,...patch}:a)});
 const submit=(type:string)=>send({type,matchId:match.id,revision:match.revision,plan});
 const order=(index:number,offset:number)=>{const ids=[...plan.controlOrder];[ids[index],ids[index+offset]]=[ids[index+offset],ids[index]];change({controlOrder:ids});};
 const killOrder=(index:number,offset:number)=>{const ids=[...plan.killOrder];[ids[index],ids[index+offset]]=[ids[index+offset],ids[index]];change({killOrder:ids});};
 const formation=(spread:number)=>change({positions:own.map((c:any,i:number)=>({id:c.id,x:match.map.minX+5+(spread===3&&i%2?3:0),y:(i-(own.length-1)/2)*spread}))});
 return <><div className="arena-preparation-heading"><div><span className="eyebrow">赛前准备 · 不限时间</span><h2>读懂阵容，安排你的打法</h2><p>{match.opponentName} · {match.size}v{match.size} · {match.map.name}</p><p>全员已自动应用 PvP 配置；可在「PvP 天赋与技能」调整，保存后同步到本场准备。</p></div><span className="arena-save-state" role="status">{dirty?'有未保存修改':'配置已保存'}</span></div>
  <div className="arena-preparation-grid"><section className="arena-tactics"><div className="arena-targets"><Choices label="集火目标" value={plan.focusId} onChange={focusId=>change({focusId})} rows={enemy}/><Choices label="控制目标" value={plan.controlId} onChange={controlId=>change({controlId})} rows={enemy}/><Choices label="爆发时机" value={plan.burst} onChange={burst=>change({burst})} rows={[{id:'controlled',name:'控制生效后爆发'},{id:'immediate',name:'持续进攻'}]}/></div>
   <details className="arena-command-settings" open><summary>控制与爆发窗口</summary><p>基础输出持续进行；爆发技能等待有效控制或法系封锁。超过等待上限则释放进攻，下一轮重新判断。</p><div className="arena-order-fields"><Choices label="最短有效控制" value={String(plan.minControlMs)} onChange={v=>change({minControlMs:Number(v)})} rows={[{id:'1000',name:'1 秒 · 积极接控'},{id:'3000',name:'3 秒 · 保留短递减控制'},{id:'5000',name:'5 秒 · 等待完整控制'}]}/><Choices label="爆发最多等待" value={String(plan.maxBurstWaitMs)} onChange={v=>change({maxBurstWaitMs:Number(v)})} rows={[{id:'8000',name:'8 秒'},{id:'12000',name:'12 秒'},{id:'20000',name:'20 秒'}]}/></div><label><input type="checkbox" checked={plan.swapOnImmunity} onChange={e=>change({swapOnImmunity:e.target.checked})}/> 目标进入完全免疫时临时转火</label></details>
   <details className="arena-chain"><summary>后续转火顺序</summary><p>先攻击集火目标；目标阵亡或完全免疫时按此顺序选择。控制目标留到最后，避免同时集火与接控。</p>{plan.killOrder.map((id:string,i:number)=><div key={id}><span>{i+1}. {enemy.find((c:any)=>c.id===id)?.name}</span><button type="button" aria-label={`上移第${i+1}位转火目标`} disabled={i===0} onClick={()=>killOrder(i,-1)}><ChevronUp size={16}/></button><button type="button" aria-label={`下移第${i+1}位转火目标`} disabled={i===plan.killOrder.length-1} onClick={()=>killOrder(i,1)}><ChevronDown size={16}/></button></div>)}</details>
   <div className="arena-section-title"><Swords size={17}/><h3>成员任务</h3><span>救援优先，脱险后恢复原任务</span></div>
   {own.map((c:any)=>{const a=plan.assignments.find((a:any)=>a.actorId===c.id);return <article className="arena-order" key={c.id}><div className="arena-fighter-name"><ClassIcon classId={c.classId} size={28}/><strong style={{color:colors[c.classId]}}>{c.name}</strong><small>{classes[c.classId]} · {roleNames[c.role]} · {c.pvpProfileName}</small></div><div className="arena-order-fields"><Choices label={`${c.name}的任务`} value={a.task} onChange={task=>assignment(c.id,{task})} rows={Object.entries(taskNames).map(([id,name])=>({id,name}))}/><Choices label={`${c.name}的打断职责`} value={a.interrupt} onChange={interrupt=>assignment(c.id,{interrupt})} rows={interruptOptions}/>{a.task==='pressure'?<Choices label={`${c.name}的压制目标`} value={a.targetId} onChange={targetId=>assignment(c.id,{targetId})} rows={enemy}/>:<Choices label={`${c.name}的保护与支援对象`} value={a.protectId} onChange={protectId=>assignment(c.id,{protectId})} rows={own}/>}</div><details><summary>追击与回撤</summary><div className="arena-order-fields"><label className="arena-label">生命低于 {a.retreatBelow}% 回撤<input aria-label={`${c.name}的回撤阈值`} type="range" min="0" max="80" step="5" value={a.retreatBelow} onChange={e=>assignment(c.id,{retreatBelow:Number(e.target.value)})}/></label><label className="arena-label">距支援对象超过 {a.leash} 码回撤<input aria-label={`${c.name}的追击距离`} type="range" min="10" max="50" step="5" value={a.leash} onChange={e=>assignment(c.id,{leash:Number(e.target.value)})}/></label></div></details></article>;})}
   <details className="arena-chain"><summary>控制接力顺序</summary><p>有成员承担控制任务时，按下列顺序协调已启用的控制技能。检查距离、视线、递减与持续伤害；避免重复接控，无法施放时由下一位接手。</p>{plan.controlOrder.map((id:string,i:number)=><div key={id}><span>{i+1}. {own.find((c:any)=>c.id===id)?.name}</span><button type="button" disabled={i===0} aria-label={`上移第${i+1}位控制手`} onClick={()=>order(i,-1)}><ChevronUp size={16}/></button><button type="button" disabled={i===plan.controlOrder.length-1} aria-label={`下移第${i+1}位控制手`} onClick={()=>order(i,1)}><ChevronDown size={16}/></button></div>)}</details>
  </section><aside><div className="arena-section-title"><Columns3 size={17}/><h3>{match.map.name}</h3></div><ArenaField map={match.map} teams={match.teams} plan={plan} preparing/><div className="arena-formation"><span>开局站位</span>{[[3,'靠前'],[5,'紧凑'],[7,'展开']].map(([spread,label])=><Button key={label} variant="outline" size="sm" onClick={()=>formation(Number(spread))}>{label}</Button>)}</div><div className="arena-section-title"><Flag size={17}/><h3>对手情报</h3><span>NPC 竞技队</span></div><div className="arena-enemy-roster">{enemy.map((c:any)=><Fighter key={c.id} unit={c} clock={0}/>)}</div><p className="arena-note">实心立柱阻挡移动与施法视线。追击绕柱时，也要保持己方治疗的支援。</p></aside></div>
  <footer className="arena-actions"><Button variant="outline" disabled={busy} onClick={()=>send({type:'arenaCancel',matchId:match.id})}>取消准备</Button><span>按当前职业、天赋与已学技能执行</span><Button variant="outline" disabled={busy} onClick={()=>submit('arenaSave')}>保存战术</Button><Button disabled={busy} onClick={()=>submit('arenaStart')}><Swords size={17}/>开始战斗</Button></footer>
 </>;
}
export default function Arena(props:GameProps){
 const {state:s,data:d,busy,send}=props,arena=useLocalArena(d.arena),match=arena?.match;
 const [section,setSection]=useState('battle');
 const [size,setSize]=useState(3),[mapId,setMapId]=useState('courtyard'),[opponentId,setOpponentId]=useState('rmp'),[selected,setSelected]=useState<string[]|null>(null);
 const roster=(arena?.roster||[]).map((c:any)=>({...c,role:d.pvp?.members.find((m:any)=>m.id===c.id)?.profile.role||c.role})),memberIds=selected||[s.id,...s.party.slice(0,size-1).map((c:any)=>c.id)];
 const active=match&&['preparing','countdown','combat'].includes(match.phase),map=arena?.maps.find((m:any)=>m.id===mapId)||arena?.maps[0];
 if(!arena)return <section className="panel">竞技场资料正在加载。</section>;
 return <div className="arena-page"><header className="arena-banner"><div className="arena-crest"><Swords size={32}/></div><div><span className="eyebrow">小队竞技 · 经典旧世</span><h1>竞技场</h1><p>控制、压制与援护。让每一次配合决定胜负。</p></div><span className="arena-banner-label">NPC 挑战</span></header><nav className="arena-page-tabs" aria-label="竞技场页面"><button type="button" aria-pressed={section==='battle'} onClick={()=>setSection('battle')}>战前指挥与比赛</button><button type="button" aria-pressed={section==='configuration'} onClick={()=>setSection('configuration')}>PvP 天赋与技能</button></nav>
  {section==='configuration'?<PvpConfiguration {...props}/>:<>
  {match?.phase==='preparing'?<Preparation key={`${match.id}:${match.revision}`} match={match} busy={busy} send={send}/>:null}
  {match&&['countdown','combat','finished'].includes(match.phase)&&<section className="arena-live"><div className="arena-live-heading"><div><span className="eyebrow">{match.size}v{match.size} · {match.map.name}</span><h2>{match.phase==='finished'?(match.result.winner===0?'胜利':match.result.winner===1?'落败':'平局'):'竞技进行中'}</h2></div><span className="arena-tactical-status" role="status">{match.tacticalStatus}</span><strong className="arena-clock">{match.phase==='countdown'?`${Math.ceil((3000-match.clock)/1000)} 秒后开门`:time(match.clock)}</strong>{match.phase!=='finished'&&<Button variant="outline" disabled={busy} onClick={()=>send({type:'arenaSurrender',matchId:match.id})}>认输</Button>}</div><div className="arena-battle-layout"><div className="arena-team own"><h3>你的小队</h3>{match.teams[0].members.map((c:any)=><Fighter key={c.id} unit={c} clock={match.clock}/>)}</div><div className="arena-character-stage"><ArenaBattle key={match.id} match={match}/><div className="arena-legend"><span><Target size={13}/> 红圈：集火</span><span><Shield size={13}/> 紫圈：控制</span><span>倒下成员淡化显示</span></div></div><div className="arena-team enemy"><h3>{match.opponentName}</h3>{match.teams[1].members.map((c:any)=><Fighter key={c.id} unit={c} clock={match.clock}/>)}</div></div><details className="arena-review" open={match.phase==='finished'}><summary>战斗记录与统计{match.result?` · ${match.result.reason}`:''}</summary><div className="arena-review-grid"><div className="arena-scoreboard"><div><b>成员</b><b>伤害</b><b>治疗</b></div>{match.metrics.map((row:any)=><div key={row.actorId}><span>{row.name}</span><span>{Math.round(row.damage)}</span><span>{Math.round(row.healing)}</span></div>)}</div><ol className="arena-log">{match.logs.slice(-25).map((e:any)=><li key={e.id}><time>{time(e.at)}</time><span>{e.text}</span></li>)}</ol></div></details></section>}
  {!active&&<section className="arena-entry"><div><div className="arena-section-title"><Swords size={18}/><h2>安排下一场挑战</h2></div><div className="arena-modes" role="group" aria-label="竞技人数">{[2,3,5].map(n=><button type="button" key={n} aria-pressed={size===n} onClick={()=>{setSize(n);setSelected(null);}}><strong>{n}v{n}</strong><small>{n===2?'双人协作':n===3?'战术核心':'完整小队'}</small></button>)}</div><Choices label="NPC 对手" value={opponentId} onChange={setOpponentId} rows={arena.opponents}/><p className="arena-note">{arena.opponents.find((o:any)=>o.id===opponentId)?.description}</p><Choices label="竞技场地图" value={mapId} onChange={setMapId} rows={arena.maps}/><div className="arena-section-title"><h3>出战名单</h3><span>{memberIds.length} / {size} 人</span></div><div className="arena-roster-picker">{roster.map((c:any)=><label key={c.id}><input type="checkbox" checked={memberIds.includes(c.id)} disabled={c.id===s.id||!c.alive||c.level!==s.level||!memberIds.includes(c.id)&&memberIds.length>=size} onChange={()=>setSelected(memberIds.includes(c.id)?memberIds.filter(id=>id!==c.id):[...memberIds,c.id])}/><ClassIcon classId={c.classId} size={25}/><span>{c.name}<small>{c.level}级 {classes[c.classId]} · {roleNames[c.role]}</small></span></label>)}</div><Button className="arena-enter" disabled={busy||!arena.unlocked||memberIds.length!==size||s.activity.type!=='idle'||!!s.combat||!!s.dungeon} onClick={()=>send({type:'arenaPrepare',size,mapId,opponentId,memberIds})}>进入准备区 <Swords size={16}/></Button><p className="arena-note">{!arena.unlocked?'18级解锁竞技场，请先培养并招募队友。':memberIds.length!==size?`需要选满${size}名出战成员。`:s.activity.type!=='idle'||s.dungeon?'请先结束当前活动并离开副本。':'准备不限时。竞技死亡与消耗不会带回冒险。'}</p></div><aside><span className="eyebrow">战场预览</span><h2>{map?.name}</h2>{map&&<ArenaField map={map}/>}<p>{map?.description}</p><div className="arena-entry-rules"><p><Target size={18}/><span><strong>先观察，再出手</strong>查看敌方职业，安排控制链和集火对象。</span></p><p><Shield size={18}/><span><strong>为队友创造空间</strong>指派保护与压制任务，设置追击和回撤条件。</span></p></div></aside></section>}
 </>}</div>;
}
