"use client";
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {GameProps,Icon,money} from './game-ui';
import ClassCompanion from './class-companion';
import CharacterEquipment from './character-equipment';
import Professions from './professions';
import {Bank,Auction} from './storage-market';
import './character.css';

const talentName=(talent:any)=>talent.nameZhCN||talent.name||talent.nameEn||'未知天赋';
const treeId=(tree:any)=>Number(tree.id??tree.tree??tree.tabId);
const treeLabels:Record<string,string>={Arms:'武器',Fury:'狂怒',Protection:'防护',Holy:'神圣',Retribution:'惩戒','Beast Mastery':'野兽掌握',Marksmanship:'射击',Survival:'生存',Assassination:'刺杀',Combat:'战斗',Subtlety:'敏锐',Discipline:'戒律',Shadow:'暗影',Elemental:'元素',Enhancement:'增强',Restoration:'恢复',Arcane:'奥术',Fire:'火焰',Frost:'冰霜',Affliction:'痛苦',Demonology:'恶魔学识',Destruction:'毁灭',Balance:'平衡','Feral Combat':'野性战斗'};
const treeName=(tree:any)=>tree.nameZhCN||treeLabels[tree.name||tree.nameEn]||tree.name||tree.nameEn||`天赋系 ${treeId(tree)}`;
const effectText=(talent:any)=>{
 const effects=talent.rankEffects||talent.effects||[];
 const effect=effects[Math.min(talent.rank||0,Math.max(0,effects.length-1))];
 return effect?.descriptionZhCN||effect?.descriptionEn||effect?.description||talent.description||'效果说明暂未收录。';
};

export default function Character({state:s,data:d,busy,send}:GameProps){
 const [section,setSection]=useState('装备与背包'),[tree,setTree]=useState<number>(0),[skillFilter,setSkillFilter]=useState('全部'),[skillSearch,setSkillSearch]=useState(''),[targetId,setTargetId]=useState('player');
 const used=Object.values(s.talents||{}).reduce((n:any,v:any)=>n+Number(v||0),0) as number;
 const trees=d.talentTrees||[],selectedTree=trees.some((item:any)=>treeId(item)===tree)?tree:treeId(trees[0]||{});
 const uses={...d.skillUses,...(d.skillUsesByTarget?.[targetId]||{})};
 const talents=d.talents||[],skills=d.skills||[],resource=d.resource||{name:'法力'};
 return <section className="armory-page"><div className="section-heading armory-page-heading"><h1>角色</h1><div className="filterbar">{['装备与背包','生活职业','银行','拍卖行','法术书','天赋'].map(t=><button className={section===t?'active':''} onClick={()=>setSection(t)} key={t}>{t}</button>)}</div></div>
 <section className="identity-summary panel" aria-label="角色身份"><div><div className="eyebrow">{d.faction==='Horde'?'部落':'联盟'} / {d.raceName}</div><h2>{d.className}</h2><p>所有种族目前共用北郡至死亡矿井的二维冒险路线。</p></div>{d.raceTraits?.length>0&&<div className="race-traits">{d.raceTraits.map((trait:any,index:number)=><div className="race-trait" key={trait.id||trait.name||index}><strong>{trait.name}</strong><small>{trait.description}</small></div>)}</div>}</section>
 {section==='装备与背包'&&<CharacterEquipment state={s} data={d} busy={busy} send={send}/>}
 {section==='生活职业'&&<Professions state={s} data={d} busy={busy} send={send}/>}
 {section==='银行'&&<Bank state={s} data={d} busy={busy} send={send}/>}
 {section==='拍卖行'&&<Auction state={s} data={d} busy={busy} send={send}/>}
 {section==='法术书'&&<><ClassCompanion state={s} data={d} busy={busy} send={send}/><section className="panel"><h2>{d.className}技能与训练</h2><p>{d.canTrain?'你在训练师附近，可以学习符合等级与前置要求的技能。':'前往北郡、闪金镇或暴风城的训练地点学习新技能。当前地图为跨种族共享改编。'}</p><p className="support-note">宠物、图腾与变形形态按当前二维战斗系统简化呈现，不包含经典旧世的全部细节。</p><div className="filterbar"><input aria-label="搜索职业技能" placeholder="搜索技能" value={skillSearch} onChange={e=>setSkillSearch(e.target.value)}/>{['全部','可学习','已学习','未学习'].map(value=><button className={value===skillFilter?'active':''} key={value} onClick={()=>setSkillFilter(value)}>{value}</button>)}<select aria-label="技能目标" value={targetId} onChange={e=>setTargetId(e.target.value)}>{[s,...s.party,...(s.pet?[s.pet]:[])].map((c:any)=><option key={c.id} value={c.id}>{c.name}{c.hp<=0?'（已死亡）':''}</option>)}{(s.combat?.enemies||[]).filter((e:any)=>e.hp>0).map((e:any)=><option key={e.id} value={e.id}>{e.name}</option>)}{!s.combat&&d.monsters.map((e:any)=><option key={e.id} value={'npc:'+e.id}>{e.name}</option>)}{s.groundEffects?.filter((e:any)=>e.trap&&e.until>s.clock).map((e:any)=><option key={e.id} value={e.id}>陷阱 · {e.name||e.id}</option>)}{d.lockTargets?.map((i:any)=><option key={i.id} value={i.id}>{i.name}</option>)}</select></div><div className="spell-list">{skills.filter((a:any)=>(!skillSearch||(a.name+' '+a.nameEn).toLowerCase().includes(skillSearch.toLowerCase()))&&(skillFilter==='全部'||skillFilter==='已学习'&&a.known||skillFilter==='可学习'&&a.canTrain||skillFilter==='未学习'&&!a.known)).map((a:any)=><div key={a.spellId} className={'spell-row '+(!a.known?'unlearned':'')+(a.supported===false?' unsupported':'')}><Icon src={a.icon} name={a.name}/><div className="grow"><strong>{a.name} {a.rank&&<small>{String(a.rank).replace('Rank','等级')}</small>}</strong><small>需要等级 {a.requiredLevel}{a.acquisitionLabel?` · ${a.acquisitionLabel}`:''}{(a.powerCost??a.manaCost)>0?` · ${a.powerCost??a.manaCost} ${a.powerName||resource.name}`:''}{a.channelMs?` · ${a.channelMs/1000} 秒引导`:a.cast?` · ${a.cast/1000} 秒施法`:' · 瞬发'}</small>{a.supported===false&&<small className="support-note">参考数据已收录，当前战斗系统尚未实现。</small>}{!a.known&&a.blockedReason&&<small className="blocked-reason">{a.blockedReason}</small>}</div>{a.known?(uses?.[a.spellId]?<div className="spell-use"><Button variant="outline" disabled={busy||!uses[a.spellId].canUse} title={uses[a.spellId].reason||uses[a.spellId].description} onClick={()=>send({type:'cast',id:a.spellId,target:targetId})}>{s.activity.spell===a.spellId&&s.activity.endsAt?'施法中…':uses[a.spellId].label}</Button><small>{uses[a.spellId].reason||uses[a.spellId].description}</small></div>:<span className="learned">已学习</span>):<Button variant="outline" disabled={busy||!a.canTrain} title={a.blockedReason||undefined} onClick={()=>send({type:'train',id:a.spellId})}>{a.acquisition==='classQuest'?'职业解锁（共用路线）':(a.costCopper>0?money(a.costCopper)+' · ':'')+'学习'}</Button>}</div>)}</div>{!skills.length&&<p className="empty">这个职业目前没有可显示的 1—60 级技能。</p>}</section></>}
 {section==='天赋'&&<section className="panel talent-panel"><div className="section-heading"><div><h2>{d.className}天赋 <small>可用 {Math.max(0,Math.min(60,s.level)-9-used)} 点 · 已投入 {used} 点</small></h2><small>10 级起每级获得 1 点；深入一层前需要在同系投入足够点数。</small></div><div className="talent-actions"><div className="filterbar">{trees.map((item:any)=><button key={treeId(item)} onClick={()=>setTree(treeId(item))} className={selectedTree===treeId(item)?'active':''}>{treeName(item)}</button>)}</div><Button variant="outline" disabled={busy||!d.canResetTalents} title={!d.canResetTalents?(d.talentResetBlockedReason||'需在训练地点拥有已投入的天赋点，并备足重置费用。'):undefined} onClick={()=>send({type:'resetTalents'})}>重置天赋{d.talentResetCost>0?` · ${money(d.talentResetCost)}`:''}</Button></div></div><div className="talent-grid">{talents.filter((t:any)=>Number(t.tree??t.treeId??t.tabId)===selectedTree).map((t:any)=><details style={{gridRow:Number(t.row??0)+1,gridColumn:Number(t.col??0)+1}} className={'talent '+(!t.canLearn&&t.rank<t.maxRank?'locked':'')+(t.supported===false?' unsupported':'')} key={t.id}><summary><Icon src={t.icon} name={talentName(t)} size={48}/><strong>{talentName(t)}</strong><span>{t.rank} / {t.maxRank}</span></summary><div className="talent-detail"><h3>{talentName(t)}</h3><p>{effectText(t)}</p><small>需要同系 {t.requiredTreePoints||0} 点</small>{t.supported===false&&<small className="support-note">参考节点；当前战斗系统尚未实现此效果。</small>}{t.blockedReason&&<small className="blocked-reason">{t.blockedReason}</small>}<Button disabled={busy||!t.canLearn} title={t.blockedReason||undefined} onClick={()=>send({type:'talent',id:t.id})}>投入 1 点</Button></div></details>)}{!talents.some((t:any)=>Number(t.tree??t.treeId??t.tabId)===selectedTree)&&<div className="talent-tree-empty">这个天赋系暂无可用节点。</div>}</div></section>}
 </section>;
}
