"use client";
import {useCallback,useEffect,useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Bar,duration,money} from './game-ui';
import World from './world';
import Character from './character';
import Strategy from './strategy';
import Battle from './battle';
import Party from './party';
import ActivityProgress from './activity-progress';
import AccountControls from './account-controls';
import {createCommandQueue} from '@/lib/command-queue.js';
import {readGameResponse,responseMatchesSelection} from '@/lib/game-response.js';
import {buildCreateCommand,classOptions,racesForClass,raceOptions} from './class-options.js';
const factionName=(faction:string)=>faction==='Horde'?'部落':'联盟';
const contentCache=new Map<string,Promise<any>>();
function loadContent(version:string){
 let pending=contentCache.get(version);
 if(!pending){pending=fetch(`/api/game/content?version=${encodeURIComponent(version)}`).then(async response=>{if(!response.ok)throw new Error('游戏内容暂时无法加载，请稍后重试。');const content:any=await response.json();if(content?.contentVersion!==version)throw new Error('游戏内容版本不匹配，请刷新页面。');return content;}).catch(error=>{contentCache.delete(version);throw error;});contentCache.set(version,pending);}
 return pending;
}
export default function Game(){
 const [connectionError,setConnectionError]=useState('');
 const[name,setName]=useState('星落'),[classId,setClassId]=useState(8),[raceId,setRaceId]=useState(1),[game,setGame]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[signedIn,setSignedIn]=useState(true),[selectedCharacter,setSelectedCharacter]=useState('');const [battleOpen,setBattleOpen]=useState(false);const manualPending=useRef(0),lastRevision=useRef(-1),selectedCharacterRef=useRef('');
 const apply=useCallback(async(data:any)=>{const expected=selectedCharacterRef.current;if(!responseMatchesSelection(data,expected,lastRevision.current))return false;const content=await loadContent(data.contentVersion);if(!responseMatchesSelection(data,selectedCharacterRef.current,lastRevision.current))return false;const actorId=data.snapshot?.player?.id||'';if(!selectedCharacterRef.current&&actorId){selectedCharacterRef.current=actorId;setSelectedCharacter(actorId);}lastRevision.current=data.revision;setGame({...data,state:data.snapshot?.player||null,view:data.snapshot?{...content,...data.snapshot.view}:null});return true;},[]);
 const pollEtags=useRef(new Map<string,string>());
 const queue=useRef<ReturnType<typeof createCommandQueue>|null>(null);
 if(!queue.current)queue.current=createCommandQueue(async(command:any)=>{const response=await fetch('/api/game',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});await apply(await readGameResponse(response));return true;});
 const send=useCallback(async(body:any)=>{manualPending.current++;setBusy(true);setError('');try{const characterId=selectedCharacterRef.current;const success=await queue.current!({...body,...(characterId?{characterId}:{}),requestId:crypto.randomUUID()});if(success)setConnectionError('');if(success&&(body.type==='hunt'||body.type==='useQuestItem'&&body.id===7308))setBattleOpen(true);return success;}catch(e:any){if(e.status===401){setSignedIn(false);setConnectionError('');setError('');return false;}setError(e.status===undefined?'连接失败，请稍后重试。':e.message);return false;}finally{manualPending.current--;setBusy(manualPending.current>0);}},[]);
 useEffect(()=>{let cancelled=false;fetch('/api/game').then(readGameResponse).then(d=>cancelled?false:apply(d)).catch(e=>{if(cancelled)return;if(e.status===401)setSignedIn(false);else setError(e.status===undefined?'连接失败，请稍后重试。':e.message);}).finally(()=>!cancelled&&setLoading(false));return()=>{cancelled=true}},[apply]);
 const selectCharacter=useCallback(async(characterId:string)=>{if(!characterId||characterId===selectedCharacterRef.current)return;pollEtags.current.delete(characterId);selectedCharacterRef.current=characterId;setSelectedCharacter(characterId);lastRevision.current=-1;setBusy(true);setError('');try{const response=await fetch(`/api/game?characterId=${encodeURIComponent(characterId)}`);await apply(await readGameResponse(response));}catch(e:any){setError(e.status===undefined?'连接失败，请稍后重试。':e.message);}finally{setBusy(false);}},[apply]);
 useEffect(()=>{if(!game?.state||!signedIn)return;let cancelled=false,running=false;const poll=async()=>{if(cancelled||running||document.visibilityState!=='visible')return;running=true;try{const characterId=selectedCharacterRef.current,etag=pollEtags.current.get(characterId),response=await fetch(`/api/game${characterId?`?characterId=${encodeURIComponent(characterId)}`:''}`,{headers:etag?{'If-None-Match':etag}:{}});if(response.status!==304){const accepted=await apply(await readGameResponse(response)),nextTag=response.headers.get('etag');if(accepted&&nextTag)pollEtags.current.set(characterId,nextTag);}if(!cancelled)setConnectionError('');}catch(e:any){if(!cancelled)setConnectionError(e.status===401?'登录已过期，请重新登录。':'暂时无法同步，正在重试。恢复连接后会更新进度。');}finally{running=false;}};const visible=()=>{if(document.visibilityState==='visible')void poll();};const timer=setInterval(()=>void poll(),1000);document.addEventListener('visibilitychange',visible);return()=>{cancelled=true;clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[!!game?.state,signedIn,selectedCharacter,apply]);
 const lastDungeonBattle=useRef<string|null>(null);
 useEffect(()=>{const b=game?.state?.combat,key=b?.dungeon?`${b.runId}:${b.startedAt}`:null;if(key&&key!==lastDungeonBattle.current)setBattleOpen(true);lastDungeonBattle.current=key;},[game?.state?.combat?.runId,game?.state?.combat?.startedAt,!!game?.state?.combat]);
 const s=game?.state,d=game?.view,props={state:s,data:d,busy,revision:game?.revision,send};const labels:any={classChannel:'引导职业技能',classSpell:'施放职业技能',mount:'召唤坐骑',escortMove:'跟随迪菲亚叛徒',prepareDungeon:'战前补给与增益',teleport:'传送中',hearth:'炉石返回中',dungeonTravel:'副本行进中',dungeonCannon:'点燃火炮',resurrect:'复活队友',idle:'等待行动',hunt:s?.combat?'战斗中':s?.rest?'补给恢复':'自动狩猎',travel:'旅行中',conjure:'制造补给',professionGather:'自动采集资源',gather:'调查中',questItem:'使用任务物品',dead:'角色已死亡',revive:'返回尸体'};
 const availableRaces=racesForClass(classId),selectedClass=classOptions.find(option=>option.id===classId)!,selectedRace=raceOptions.find(option=>option.id===raceId)||availableRaces[0];
 const resource=d?.resource||{name:'法力',value:s?.mana||0,max:d?.stats?.maxMana||0},resourceTone=resource.name==='怒气'?'rage':resource.name==='能量'?'energy':'mana';
 return <main className="game-shell"><header className="masthead"><a href="/" className="wordmark">WOW<span>SIM</span></a><span className="edition">经典旧世 · 2019 / 第一阶段</span><span className="online-dot">{signedIn?'云端存档':'等待登录'}</span></header>
 {!signedIn&&s&&<section className="activity-strip" role="alert"><span>登录已过期，请重新登录以继续冒险。</span><Button asChild><a href="/login">重新登录 →</a></Button></section>}
 {signedIn&&connectionError&&s&&<div className="activity-strip" role="status">{connectionError}</div>}
 {(!s||!d)?<section className="arrival"><div className="eyebrow">第一章 / 共同的起点</div><h1>选择你的道路，<br/><em>从北郡启程。</em></h1><p>九种经典职业与八个可玩种族，都在同一张北郡冒险地图中展开。<br/>这是清晰的二维改编，不代表各族原生出生区域已实现。</p><div className="creation panel"><div className="identity-crest" aria-hidden="true">{selectedClass.name.slice(0,1)}</div><div><h2>{selectedRace.name} · {selectedClass.name}</h2><p>{factionName(selectedRace.faction)} · 共享北郡地图 · 等级 1</p></div><div className="creation-selects"><label>职业<select aria-label="职业" value={classId} onChange={e=>{const next=Number(e.target.value),races=racesForClass(next);setClassId(next);if(!races.some(r=>r.id===raceId))setRaceId(races[0].id);}}>{classOptions.map(option=><option key={option.id} value={option.id}>{option.name}</option>)}</select></label><label>种族<select aria-label="种族" value={selectedRace.id} onChange={e=>setRaceId(Number(e.target.value))}>{availableRaces.map(option=><option key={option.id} value={option.id}>{option.name} · {factionName(option.faction)}</option>)}</select></label></div><label>角色名字<input aria-label="角色名字" maxLength={16} value={name} onChange={e=>setName(e.target.value)}/></label>{signedIn?<Button disabled={busy||loading||!name.trim()} onClick={()=>send(buildCreateCommand(name,classId,selectedRace.id))}>{loading?'读取存档…':'踏入艾泽拉斯 →'}</Button>:<Button asChild><a href="/login">登录并开始冒险 →</a></Button>}</div><div className="creation-notes"><span>01 九种经典职业</span><span>02 合法种族组合</span><span>03 共享北郡改编</span></div></section>:<>
 {(game.roster?.length>1||game.activities?.length>0)&&<section className="panel account-overview" aria-label="账号角色与活动"><div className="section-heading"><div><div className="eyebrow">账号队伍</div><h2>角色与后台活动</h2></div>{game.roster?.length>1&&<label>当前角色 <select aria-label="当前角色" value={selectedCharacter||s.id} disabled={busy} onChange={event=>void selectCharacter(event.target.value)}>{game.roster.map((member:any)=><option key={member.id} value={member.id}>{member.name} · Lv.{member.level}</option>)}</select></label>}</div>{game.activities?.length>0&&<div className="activity-roster">{game.activities.map((activity:any)=>{const actor=game.roster?.find((member:any)=>member.id===activity.actorId);return <div key={activity.id}><strong>{actor?.name||activity.actorId}</strong><span>{activity.type} · {activity.status}{activity.location?` · ${activity.location}`:''}</span>{activity.nextEventAt&&<small>下次结算 {new Date(activity.nextEventAt).toLocaleTimeString()}</small>}{['craft','gather'].includes(activity.type)&&['running','returning'].includes(activity.status)&&<Button size="sm" variant="outline" disabled={busy||activity.status==='returning'} onClick={()=>send({type:'recall',activityId:activity.id})}>{activity.status==='returning'?'召回中':'召回'}</Button>}</div>})}</div>}</section>}
 <AccountControls game={game} busy={busy} send={send}/>
 <section className="character-header"><div className="identity-crest compact" aria-hidden="true">{d.className?.slice(0,1)||'勇'}</div><div className="character-name"><h2>{s.name} <span className="level-badge">{s.level}</span></h2><small>{d.raceName} · {d.className} · {factionName(d.faction)}</small><span className="wallet">{money(s.money)}</span></div><div className="resource-stack"><Bar label="生命" value={s.hp} max={d.stats.maxHp}/>{resource.max>0&&<Bar label={resource.name} value={resource.value} max={resource.max} tone={resourceTone}/>}</div><div className="xp-summary"><small>{s.level>=60?'等级上限':'距离下一级'}</small><strong>{s.level>=60?'Lv.60':`${s.xp} / ${d.nextXp}`}</strong><Bar label="经验" value={s.xp} max={d.nextXp||1} tone="xp"/></div></section>
 <section className="activity-strip" aria-live="polite"><span className={'activity-light '+s.activity.type}/><div className="grow"><strong>{s.combat?'战斗中':labels[s.activity.type]||s.activity.type}</strong><span> · {d.location.name}{s.activity.to?' → '+d.map.find((n:any)=>n.id===s.activity.to)?.name:''}</span><small>{s.activity.reason|| (s.activity.endsAt?`剩余 ${duration(s.activity.endsAt-s.clock)}`:s.dungeon?'副本战斗在后台继续，每场结束后等待队长继续推进。':'野外活动离线继续，补给不足时自动停止。')}</small></div>{s.hp<=0?<><Button onClick={()=>send({type:'revive'})} disabled={busy||!!s.combat}>复活</Button>{d.canSoulstoneRevive&&<Button onClick={()=>send({type:'soulstoneRevive'})} disabled={busy}>灵魂石复活</Button>}{d.reincarnation&&<Button title={d.reincarnation.reason} onClick={()=>send({type:'reincarnate'})} disabled={busy||!d.reincarnation.canUse}>复生</Button>}</>:<Button variant="outline" onClick={()=>send({type:'stop'})} disabled={busy||s.activity.type==='idle'&&!s.rest||s.activity.flight&&s.activity.stopAtNext}>{s.activity.flight?(s.activity.stopAtNext?'已申请下一站停靠':'下一飞行点停靠'):'停止'}</Button>}</section>
 <ActivityProgress state={s} data={d} running/>
 {(s.combat||s.lastCombat)&&<Button className="enter-battle" variant="outline" onClick={()=>setBattleOpen(true)}>进入战斗界面 ⚔</Button>}{(s.combat||s.lastCombat)&&<Battle {...props} open={battleOpen} onOpenChange={setBattleOpen}/>}{s.combat&&<section className="combat-strip"><div className="eyebrow">实时战斗</div>{s.combat.enemies.filter((e:any)=>!e.dead).map((e:any)=><div className="enemy-status" key={e.id}><strong>{e.name} <small>Lv.{e.level}</small></strong><Bar label="生命" value={e.hp} max={e.maxHp}/></div>)}{s.cast&&<p>{d.skills.find((a:any)=>a.spellId===s.cast.spell)?.name||'施法'} · {duration(s.cast.until-s.clock)}</p>}</section>}
 <Tabs defaultValue="world" className="game-tabs"><TabsList className="main-nav"><TabsTrigger value="world">世界</TabsTrigger><TabsTrigger value="character">角色</TabsTrigger><TabsTrigger value="party">队伍</TabsTrigger><TabsTrigger value="strategy">策略</TabsTrigger><TabsTrigger value="log">战报</TabsTrigger></TabsList><TabsContent value="world"><World {...props}/></TabsContent><TabsContent value="character"><Character {...props}/></TabsContent><TabsContent value="party"><Party {...props}/></TabsContent><TabsContent value="strategy"><Strategy {...props}/></TabsContent><TabsContent value="log"><section className="panel"><div className="section-heading"><h2>战斗与旅程记录</h2><small>击杀 {s.totals.kills} · 获得经验 {s.totals.xp}</small></div><div className="combat-log">{[...s.logs].reverse().map((l:any)=><div key={l.id} className={'log-'+l.kind}><time>{duration(l.at)}</time><span>{l.text}</span></div>)}</div></section></TabsContent></Tabs>
 </>}{error&&<div className="error toast" role="alert">{error}<button aria-label="关闭提示" onClick={()=>setError('')}>×</button></div>}<footer><span>1—60 级 · 九职业经典旅程</span><span>共享北郡地图 · 社区经典数据参考 · 2D 冒险改编</span></footer></main>
}
