import {useEffect,useState} from 'react';
import {Dialog} from 'radix-ui';
import {Gift,X} from 'lucide-react';
import {saveFetch} from '../lib/save-fetch';
import './gm-gifts.css';
type Parcel={id:string;gift:{name:string;description:string;copper:number;items:{id:number;count:number;name:string;icon:string}[]}};
export default function GmGifts({characterId,busy,send,error,onBag}:{characterId:string;busy:boolean;send:(command:Record<string,unknown>)=>Promise<boolean>;error:string;onBag:()=>void}){
 const [gifts,setGifts]=useState<Parcel[]>([]),[open,setOpen]=useState(false),[failure,setFailure]=useState(''),[success,setSuccess]=useState(''),[claiming,setClaiming]=useState(false);
 async function refresh(){const response=await saveFetch('/api/game/gm-inbox');const data=await response.json();if(!response.ok)throw new Error(data.error||'礼包加载失败');if(!Array.isArray(data.gifts))throw new Error('礼包响应格式异常，请稍后重试');setGifts(data.gifts);setFailure('');}
 useEffect(()=>{let active=true;const controller=new AbortController();const load=async()=>{try{const response=await saveFetch('/api/game/gm-inbox',{signal:controller.signal});const data=await response.json();if(!response.ok)throw new Error(data.error||'礼包加载失败');if(!Array.isArray(data.gifts))throw new Error('礼包响应格式异常，请稍后重试');if(active){setGifts(data.gifts);setFailure('');}}catch(e){if(active)setFailure((e as Error).message);}};void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);const visible=()=>{if(document.visibilityState==='visible')void load();};document.addEventListener('visibilitychange',visible);return()=>{active=false;controller.abort();clearInterval(timer);document.removeEventListener('visibilitychange',visible);};},[characterId]);
 return <Dialog.Root open={open} onOpenChange={value=>{if(!claiming){setOpen(value);setSuccess('');}}}>{gifts.length>0&&<Dialog.Trigger asChild><button className={`gm-gift-trigger${gifts.length?' has-gifts':''}`} aria-label={`奖励中心，${gifts.length} 个待领取礼包`}><Gift size={19}/><span>奖励{gifts.length>0&&<b>{gifts.length}</b>}</span></button></Dialog.Trigger>}<Dialog.Portal><Dialog.Overlay className="gm-gift-backdrop"/><Dialog.Content className="gm-gift-dialog"><header><Dialog.Title>奖励中心</Dialog.Title><Dialog.Close disabled={claiming} aria-label="关闭奖励中心"><X size={20}/></Dialog.Close></header><Dialog.Description>礼包领取到当前角色。背包空间不足时请先清理，物品和金币会全部保留，稍后可重新领取。</Dialog.Description>{failure&&<p role="alert">{failure}<button onClick={()=>void refresh().catch(e=>setFailure(e.message))}>重试</button></p>}{error&&<p className="gm-gift-error" role="alert">{error}</p>}{success&&<p role="status">{success}</p>}
 <div className="gm-gift-list">{gifts.length===0&&<p>暂无待领取礼包。</p>}{gifts.map(parcel=><article key={parcel.id}><h3>{parcel.gift.name}</h3><p>{parcel.gift.description}</p><ul>{parcel.gift.items.map(item=><li key={item.id}>{item.icon&&<img src={item.icon} alt=""/>}{item.name}<b>×{item.count}</b></li>)}</ul>{parcel.gift.copper>0&&<p className="gm-gift-gold">金币：{parcel.gift.copper/10000} 金</p>}<button disabled={busy||claiming} onClick={async()=>{setClaiming(true);setSuccess('');try{if(await send({type:'claimGmGift',id:parcel.id})){setSuccess(`已领取「${parcel.gift.name}」。`);await refresh();}}catch(e){setFailure((e as Error).message);}finally{setClaiming(false);}}}>{claiming?'正在领取…':'领取全部奖励'}</button></article>)}</div><footer><button disabled={busy||claiming} onClick={()=>{setOpen(false);onBag();}}>打开背包清理</button><button disabled={claiming} onClick={()=>void refresh().catch(e=>setFailure(e.message))}>刷新礼包</button></footer></Dialog.Content></Dialog.Portal></Dialog.Root>;
}
