'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {GameSelect,GameSelectOption} from '@/components/ui/game-select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Bar,Item,ItemDisplay,money,duration,type GameProps} from './game-ui';
import './gold-raid.css';
import RaidCommandPanel from './raid-command';
import DungeonMap from './dungeon-map';
const roles:Record<string,string>={tank:'坦克',healer:'治疗',melee:'近战输出',ranged:'远程输出'};
const skills:Record<string,string>={novice:'初来乍到',regular:'熟练团员',expert:'竞速老手'};
const classes:Record<number,string>={1:'战士',2:'圣骑士',3:'猎人',4:'盗贼',5:'牧师',7:'萨满',8:'法师',9:'术士',11:'德鲁伊'};
const phaseNames:Record<string,string>={draft:'拟定团规',recruiting:'招募大厅',camp:'首领营地',combat:'战斗进行中',settled:'分金完成'};
const amount=(v:number)=>`${(v/10000).toLocaleString('zh-CN',{maximumFractionDigits:4})} 金`;
function Auction({state:s,data:d,busy,send,onPass}:GameProps&{onPass:()=>void}){
 const g=d.goldRaid,a=g.auction,item=d.items[a.itemId],eligible=g.core.filter((c:any)=>c.canBid);
 const [target,setTarget]=useState(eligible[0]?.id||''),[offer,setOffer]=useState('');
 const bidValue=offer===''?a.minimum:Math.round(Number(offer)*10000),leading=a.leader==='player';
 return <section className="panel gold-auction" aria-label="金团拍卖"><div className="eyebrow">公开竞价 · 尚有 {a.remainingLots} 件待拍</div><h2>{a.rare?'✦ 传说战利品':'战利品'} ×{a.count}</h2><div className="gold-auction-loot"><ItemDisplay item={item||{name:a.name}} instance={{count:a.count}} auction/></div>
 <p className="gold-auction-eligible">你可以竞拍：{eligible.length?eligible.map((c:any)=>c.name).join('、'):'当前无人符合限制'}</p><div className="gold-bid-current"><strong>{amount(a.price||a.minimum)}</strong><span>{a.winner?`当前领先：${a.winner}`:'等待首次出价'} · 连续无人加价 {a.quiet} / 3</span></div><p>每4秒一轮询价；连续三轮无人加价自动落槌。出价即时托管，被超过全额退回，成交才计入金池。拍品成交后领取；装备可分配给角色，材料和任务起始物品保存在背包。</p>{a.bidNotice&&<p role="status">{a.bidNotice}</p>}<div className="gold-bid-inputs"><label>为谁竞拍<GameSelect value={target} onValueChange={setTarget} aria-label="竞拍物品的角色" disabled={busy||!eligible.length}>{eligible.length?eligible.map((c:any)=><GameSelectOption value={c.id} key={c.id}>{c.name}</GameSelectOption>):<GameSelectOption value="">当前角色无法使用</GameSelectOption>}</GameSelect></label><label>出价（金币）<input type="number" min={a.minimum/10000} step={a.step/10000} value={offer} placeholder={String(a.minimum/10000)} onChange={e=>setOffer(e.target.value)}/></label></div><small>可用金币：{money(s.money)} · 最低出价 {amount(a.minimum)} · 最低加价 {amount(a.step)}</small>{offer!==''&&bidValue<a.minimum&&<p role="status">你的报价已低于最低价。<Button variant="ghost" onClick={()=>setOffer('')}>使用最新最低价</Button></p>}<div className="action-row"><Button disabled={busy||leading||!target||!Number.isSafeInteger(bidValue)||bidValue<a.minimum||bidValue>s.money} onClick={()=>send({type:'goldBid',lotId:a.id,amount:bidValue,quotedMinimum:a.minimum,recipient:target})}>{leading?'你已领先':`出价 ${amount(bidValue)}`}</Button><Button variant="outline" disabled={busy||leading} onClick={async()=>{if(await send({type:'goldPass',lotId:a.id}))onPass();}}>暂不竞拍并折叠</Button><Button variant="ghost" disabled={busy} onClick={()=>send({type:'goldAuctionStep',lotId:a.id})}>推进一轮询价</Button></div><ol className="gold-bid-history">{a.bids.slice().reverse().map((b:any,i:number)=><li key={i}><span>{b.name}</span><b>{amount(b.amount)}</b></li>)}</ol></section>;
}
export function GoldAuctionPanel(props:GameProps){
 const {data:d}=props,g=d.goldRaid;
 const [auctionCollapsed,setAuctionCollapsed]=useState(false);
 return <section className="gold-auction-panel" aria-label="后台拍卖">
  <button type="button" className="gold-auction-toggle" aria-expanded={!auctionCollapsed} aria-controls="gold-auction-body" onClick={()=>setAuctionCollapsed(!auctionCollapsed)}>
   <span><ItemDisplay item={d.items[g.auction.itemId]||{name:g.auction.name}} instance={{count:g.auction.count}} auction/><small>{amount(g.auction.price||g.auction.minimum)} · {g.auction.leader==='player'?'你当前领先':g.auction.winner?`${g.auction.winner}领先`:'等待出价'} · 待拍 {g.auction.remainingLots} 件 · 拍卖不影响继续战斗</small></span><b>{auctionCollapsed?'展开竞拍 ＋':'折叠竞拍 −'}</b>
  </button>
  <div id="gold-auction-body" hidden={auctionCollapsed}><Auction key={g.auction.id} {...props} onPass={()=>setAuctionCollapsed(true)}/></div>
 </section>;
}
export default function GoldRaid(props:GameProps&{onObserve:()=>void}){
 const {state:s,data:d,busy,send,onObserve}=props,g=d.goldRaid;
 const [inspect,setInspect]=useState<any>(null),[fee,setFee]=useState(5),[dps,setDps]=useState(10),[support,setSupport]=useState(10),[filter,setFilter]=useState('all'),[priority,setPriority]=useState('balanced'),[confirm,setConfirm]=useState(false);
 if(!g)return null;
 if(!g.active)return <section className="panel gold-entry"><div className="eyebrow">25 人 · 持久冒险者 · 公开分金</div><h2>组织你的金团</h2><p>你与24名 NPC 玩家同行。邀请熟悉的好友，查看真实装备和钱包；他们拍得的装备、花费的金币与参团经历都会留到下一次冒险。</p><div className="gold-pills"><span>1. 公布规则</span><span>2. 邀请冒险者</span><span>3. 挑战与竞拍</span><span>4. 各自分金</span></div><div className="gold-entry-raids">{g.raids.map((raid:any)=><article key={raid.id}><h3>{raid.name}</h3><p>本周进度 {raid.cleared} / {raid.bossCount} · 散团后保留</p><Button disabled={busy||!raid.canEnter} onClick={()=>send({type:'enterDungeon',contentId:raid.id})}>创建金团</Button>{raid.reason&&<small>{raid.reason}</small>}</article>)}</div><small>60级团长即可开团，无需预先组满五人。击杀进度每周重置，团员资产持续保存。</small></section>;
 const locked=busy||!!s.combat||g.recovering,applicants=g.applicants.filter((c:any)=>filter==='all'||c.role===filter),selected=g.selected||[];
 return <div className="gold-page"><header className="panel gold-masthead"><div><div className="eyebrow">25 PLAYERS / GDKP</div><h1>{g.name} · 金团</h1><p>{phaseNames[g.phase]} · {s.name} 的25人团队</p></div><div className="gold-pot"><small>{g.phase==='settled'?'本团已分配':'已成交金池'}</small><strong>{amount(g.pot)}</strong><span>{g.cleared.length} / {g.bosses.length} 首领</span></div></header>
 {['camp','combat'].includes(g.phase)&&<RaidCommandPanel {...props}/>}
 {g.phase!=='draft'&&<div className="gold-contract"><b>已公告并锁定</b><span>团长 {g.rules.leaderFee}%</span><span>DPS前三 {g.rules.dpsBonus}%</span><span>坦奶 {g.rules.supportBonus}%</span><span>余款 {100-g.rules.leaderFee-g.rules.dpsBonus-g.rules.supportBonus}% 按人均分</span></div>}
 {g.phase==='draft'&&<section className="panel gold-rules"><div className="eyebrow">01 / 开团公告</div><h2>先把规矩讲清楚</h2><p>补助从成交金池中划分。NPC 的装备与熟练度来自持续冒险；坦奶和输出奖金达到10%时，会鼓励对应职责的团员自费用药。</p><div className="gold-rule-inputs">{[{name:'团长抽成',value:fee,set:setFee,max:10},{name:'DPS前三奖金池',value:dps,set:setDps,max:20},{name:'坦克与治疗补助池',value:support,set:setSupport,max:20}].map(r=><label key={r.name}>{r.name}<div><input type="range" min="0" max={r.max} step="5" value={r.value} onChange={e=>r.set(Number(e.target.value))}/><strong>{r.value}%</strong></div></label>)}</div><p>剩余 <b>{100-fee-dps-support}%</b> 按参战人数均分。你和每名参战 NPC 各占一份，NPC 分红进入自己的钱包；DPS奖金由非坦奶总伤害前三平分，坦奶补助由所有坦克与治疗平分。只有成功击杀的战斗计入奖金排名，不扣死亡罚金。</p><div className="action-row"><Button disabled={busy} onClick={async()=>{if(await send({type:'goldRules',rules:{leaderFee:fee,dpsBonus:dps,supportBonus:support}}))await send({type:'goldPublish'});}}>发布公告 · 开始收人</Button><Button variant="outline" disabled={busy} onClick={()=>send({type:'goldSettle'})}>取消开团</Button></div></section>}
 {g.phase==='recruiting'&&<section className="panel"><div className="section-heading"><div><div className="eyebrow">02 / 招募大厅</div><h2>冒险者名册</h2></div><strong>已录取 {selected.length} / {g.requiredSeats}</strong></div><p>你占一个席位，另邀请24名60级冒险者。当前阵容：{g.roles.tank}坦克 / {g.roles.healer}治疗 / {g.roles.damage}输出。熟练玩家、富裕买家与分金党各有价值。</p><div className="gold-recruit-tools"><GameSelect value={filter} onValueChange={setFilter} aria-label="筛选申请职责"><GameSelectOption value="all">所有职责</GameSelectOption>{Object.entries(roles).map(([key,name])=><GameSelectOption key={key} value={key}>{name}</GameSelectOption>)}</GameSelect><GameSelect value={priority} onValueChange={setPriority} aria-label="组团偏好"><GameSelectOption value="balanced">均衡阵容</GameSelectOption><GameSelectOption value="progress">优先熟练度</GameSelectOption><GameSelectOption value="buyers">优先购买力</GameSelectOption><GameSelectOption value="friends">优先好友</GameSelectOption></GameSelect><Button variant="outline" disabled={busy} onClick={()=>send({type:'goldRecommend',priority})}>推荐25人阵容</Button></div><div className="gold-recruit-footer"><Button disabled={busy||selected.length!==g.requiredSeats||g.roles.tank<2||g.roles.healer<5} onClick={()=>send({type:'goldLaunch'})}>名单锁定 · 进入营地</Button><small>开打后不能换人或修改分金规则。至少2坦克、5治疗。</small></div><div className="gold-applicants">{applicants.map((c:any)=><article className={'gold-applicant '+(selected.includes(c.id)?'is-selected':'')} key={c.id}><div className="section-heading"><strong>{c.friend?'★ ':''}{c.name}</strong><span>{roles[c.role]}</span></div><p>{classes[c.classId]} · {skills[c.skill]} · {c.quality}装备</p><div className="gold-personality"><b>{c.personalityName}</b><span>{amount(c.wallet)}</span></div><small>与你同行 {c.runs} 次 · “{c.quote}”</small><p>{c.trees.map((t:any)=>`${t.name} ${t.points}`).join(' / ')}</p><div className="action-row"><Button size="sm" variant="outline" onClick={()=>setInspect(c)}>查看装备与天赋</Button><Button size="sm" variant={selected.includes(c.id)?'outline':'default'} disabled={busy||!selected.includes(c.id)&&selected.length>=g.requiredSeats} onClick={()=>send({type:'goldInvite',id:c.id})}>{selected.includes(c.id)?'取消录取':'录取'}</Button></div></article>)}</div></section>}
 {g.auction&&<GoldAuctionPanel {...props}/>}
 {['camp','combat'].includes(g.phase)&&<><DungeonMap {...props} raid="gold"/>{g.phase==='combat'&&<section className="panel"><h2>团队正在交战</h2><div className="gold-pills">{g.nextMechanics.map((m:any)=><span key={m.name}>{m.name} · {duration(m.at-s.clock)}</span>)}</div><div className="action-row"><Button onClick={onObserve}>观察战场与伤害统计</Button><Button variant="outline" disabled={busy} onClick={()=>send({type:'abandonCombat',encounterId:s.combat.id})}>撤退重整</Button></div></section>}{g.phase==='camp'&&<section className="panel"><div className="section-heading"><h2>团长指挥台</h2><span>{g.recovering?`休整中 · ${duration(g.remaining)}`:'战前整备'}</span></div><p>在开荒指挥台为首领发布分工。NPC按自己的操作水平执行；药剂与药水仍由团员自费购买。</p><div className="action-row"><Button variant="outline" disabled={locked} onClick={()=>send({type:'goldRecover'})}>全团休整 · 10秒</Button>{s.pending.length>0&&<Button disabled={busy} onClick={()=>send({type:'loot'})}>领取拍得装备（{s.pending.length}）</Button>}{s.lastCombat&&<Button variant="outline" onClick={onObserve}>查看战报</Button>}</div></section>}</>}
 {!g.settlement&&!!g.members.length&&<section className="panel"><div className="section-heading"><h2>团队名册</h2><small>{g.roles.tank}坦 / {g.roles.healer}治疗 / {g.roles.damage}输出</small></div><div className="gold-member-list">{g.members.map((c:any)=><button key={c.id} onClick={()=>setInspect(c)}><div><strong>{c.name}</strong><small>{roles[c.role]} · {skills[c.skill]}</small></div><Bar label="生命" value={c.hp} max={c.maxHp}/><div><span>DPS {Math.round(c.dps)}</span><span>自费用药 {amount(c.consumableSpent)}</span></div><small>火区受伤 {c.fireHits}次 · 倒下 {c.deaths}次</small></button>)}</div></section>}
 {g.settlement&&<section className="panel gold-settlement"><div className="eyebrow">04 / 公开账本</div><h2>分金完成</h2><p>成交总额 <b>{amount(g.settlement.pot)}</b> · 团长抽成 {amount(g.settlement.fee)} · 你实际到账 <b>{amount(g.settlement.playerIncome)}</b></p><div className="gold-table-wrap"><table><thead><tr><th>成员</th><th>基础分红</th><th>DPS奖金</th><th>坦奶补助</th><th>合计</th></tr></thead><tbody>{g.settlement.rows.map((r:any)=><tr key={r.id}><td>{r.name}{r.core?' · 你':''}</td><td>{amount(r.base)}</td><td>{amount(r.dpsBonus)}</td><td>{amount(r.supportBonus)}</td><td>{amount(r.total)}</td></tr>)}</tbody></table></div><div className="action-row">{s.pending.length>0&&<Button disabled={busy} onClick={()=>send({type:'loot'})}>领取拍得装备</Button>}<Button disabled={busy} onClick={()=>send({type:'leaveInstance'})}>结束金团 · 返回世界</Button></div></section>}
 <div className="gold-bottom"><section className="panel"><h2>团队频道</h2><div className="gold-chat" role="log">{g.chat.slice(-12).reverse().map((line:any,i:number)=><p key={i}>{line.text}</p>)}</div></section><section className="panel"><h2>成交记录</h2>{g.sales.length?g.sales.map((sale:any)=><div className="gold-sale" key={sale.id}><ItemDisplay item={d.items[sale.itemId]||{name:sale.name}} instance={{count:sale.count}}/><span>{sale.winner} · {amount(sale.price)}</span></div>):<p>战利品将逐件公开竞拍。常规装备和稀有毕业装备的心理价不同，土豪也有钱包上限。</p>}</section></div>
 {['camp','recruiting'].includes(g.phase)&&<footer className="panel"><p>可以提前散团，但必须先拍完当前掉落，再把已成交金币按公告分给参战者。团灭不扣分金资格。</p>{confirm?<div className="action-row"><Button disabled={locked||!!g.auction} onClick={()=>{setConfirm(false);send({type:'goldSettle'});}}>确认结算并结束本团</Button><Button variant="outline" onClick={()=>setConfirm(false)}>继续带团</Button></div>:<Button variant="outline" disabled={locked||!!g.auction} onClick={()=>setConfirm(true)}>{g.cleared.length===g.bosses.length?'全通 · 结算分金':'提前散团并结算'}</Button>}</footer>}
 <Dialog open={!!inspect} onOpenChange={open=>{if(!open)setInspect(null);}}><DialogContent className="gold-inspect"><DialogTitle>{inspect?.name} · 玩家档案</DialogTitle><DialogDescription>大厅中的同一位冒险者；装备、钱包与参团经历持续保存。</DialogDescription>{inspect&&<><p>{classes[inspect.classId]} · {roles[inspect.role]} · {skills[inspect.skill]} · {inspect.personalityName}</p><p>携带 {amount(inspect.wallet)} · {inspect.trees.map((t:any)=>`${t.name} ${t.points}`).join(' / ')}</p><h3>装备</h3><div className="gold-inspect-items">{inspect.equipment.map((e:any)=><div key={e.slot}><Item item={d.items[e.id]}/></div>)}</div><h3>天赋分配</h3><div className="gold-talents">{inspect.talents.map((t:any)=><span key={t.id}>{t.name} <b>{t.rank}/{t.maxRank}</b></span>)}</div></>}</DialogContent></Dialog>
 </div>;
}
