'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Bar,GameProps,duration} from './game-ui';
import './guild-raid.css';
import RaidCommandPanel from './raid-command';
import DungeonMap from './dungeon-map';

const roleNames:Record<string,string>={tank:'坦克',healer:'治疗',melee:'近战',ranged:'远程'};
export default function GuildRaid({state:s,data:d,busy,send,onObserve}:GameProps&{onObserve:()=>void}){
 const [confirm,setConfirm]=useState(false),r=d.guildRaid;
 if(!r)return null;
 const fighting=!!s.combat,locked=busy||fighting||r.recovering,last=r.attempts.at(-1);
 if(!r.active)return <section className="panel guild-entry" aria-label="经典团队副本入口"><div className="section-heading"><div><div className="eyebrow">60级 · 公会远征</div><h2>经典团队副本</h2></div><span className="guild-size">25人</span></div><p>带上核心五人队，公会提供20名战友。两座团本分别保存每周进度和奖励资格。</p><div className="guild-raid-choices">{r.raids.map((raid:any)=><article key={raid.id} style={{backgroundImage:`linear-gradient(0deg,rgba(9,15,19,.95),rgba(9,15,19,.3)),url(/journal/dungeons/${raid.id}.webp)`}}><h3>{raid.name}</h3><p>{raid.bossCount} 名首领 · 独立周进度</p><Button disabled={busy||!r.canEnter||!!raid.attunementReason} onClick={()=>send({type:'enterDungeon',contentId:raid.id,capacity:25})}>集结公会 · 进入</Button>{raid.attunementReason&&<p className="footnote">{raid.attunementReason}</p>}</article>)}</div><p className="footnote">需要五名存活的60级核心队员。采用本作25人战斗数值；每周奖励一次，退出和团灭保留进度。</p></section>;
 return <div className="guild-expedition">
  <header className="panel guild-header"><div className="section-heading"><div><div className="eyebrow">经典旧世 · 公会远征</div><h1>{r.name}</h1><p>核心5人＋公会20人 · 单人指挥</p></div><div className="guild-progress"><strong>{r.cleared.length}<small> / {r.bosses.length}</small></strong><span>首领已击败</span></div></div><div className="guild-command-bar"><span>{r.roles.tank} 坦克 · {r.roles.healer} 治疗 · {r.roles.damage} 输出</span><Button variant="outline" disabled={locked} onClick={()=>send({type:'leaveInstance'})}>离开并保存进度</Button></div></header>
  <RaidCommandPanel state={s} data={d} busy={busy} send={send}/>
  <DungeonMap state={s} data={d} busy={busy} send={send} raid="guild"/>
  <section className="panel guild-live" aria-label="远征当前状态"><div className="section-heading"><h2>{fighting?'战斗进行中':r.recovering?'营地休整中':r.cleared.length===r.bosses.length?r.name+'全通':'远征营地'}</h2><span>{r.members.filter((m:any)=>m.hp>0).length} / 25 存活</span></div>{fighting?<><div className="guild-countdowns">{r.nextMechanics.map((m:any)=><span key={m.name}>{m.name}<b>{duration(Math.max(0,m.at-s.clock))}</b></span>)}</div><div className="action-row"><Button onClick={onObserve}>观察战场与伤害统计</Button><Button variant="outline" disabled={busy} onClick={()=>send({type:'abandonCombat',encounterId:s.combat.id})}>放弃本次挑战</Button></div><p className="footnote">战斗由服务器持续结算。关闭战斗窗口仍会继续；放弃按全员倒下结算。</p></>:<><p>{r.recovering?`公会正在复活队员、补充饮水和弹药，还需 ${duration(r.remaining)}`:s.activity.reason||'调整战术后再发起挑战，每次开战会补满生命、法力和弹药。'}</p><div className="action-row"><Button variant="outline" disabled={locked} onClick={()=>send({type:'raidRecover'})}>全团休整 · 10秒</Button>{s.pending.length>0&&<Button disabled={busy||r.recovering} onClick={()=>send({type:'loot'})}>拾取战利品（{s.pending.length}）</Button>}{s.lastCombat&&<Button variant="outline" onClick={onObserve}>查看上场战报</Button>}</div></>}
  {last&&!fighting&&<div className={'guild-result '+(last.won?'win':'')} role="status"><strong>{last.won?'遭遇完成':last.abandoned?'已放弃挑战':'挑战失败'}</strong><span>{duration(last.duration)} · {last.deaths}人倒下 · 驱散{last.support.dispels}次 · 宁神{last.support.tranquilizes}次</span>{last.failures.doom>0&&<p>{last.failures.doom}次末日未驱散，检查驱散策略与法力消耗。</p>}{last.failures.fire>0&&<p>承受{last.failures.fire}次熔岩伤害，注意躲火与恐惧叠加。</p>}</div>}
  </section>
  <div className="guild-camp-grid"><section className="panel guild-events"><h2>机制记录</h2>{r.events.length?r.events.slice().reverse().map((e:any,i:number)=><p key={i}><time>{duration(Math.max(0,e.at-(s.combat||s.lastCombat)?.startedAt))}</time>{e.text}</p>):<p>首领施放机制、队友驱散与失败原因会记录在这里。</p>}</section></div>
  <section className="panel"><div className="section-heading"><h2>公会编队</h2><small>五支小队，共享战场与治疗</small></div><div className="guild-squads">{r.squadNames.map((name:string,index:number)=><section key={name}><h3>0{index+1} · {name}</h3><p className="footnote">{index===0?'自己的角色与装备':'公会支援队员'}</p>{r.members.filter((m:any)=>m.squad===index).map((m:any)=><article key={m.id} className={m.hp<=0?'is-fallen':''}><div><strong>{m.name}</strong><small>{roleNames[m.role]}</small></div><Bar label="生命" value={m.hp} max={m.maxHp}/>{m.maxMana>0&&<Bar label="法力" value={m.mana} max={m.maxMana} tone="mana"/>}</article>)}</section>)}</div></section>
  <footer className="panel guild-footer"><p>本周进度保存在角色存档；奖励于 {new Date(r.weekResetAt).toLocaleString()} 后重新进入时刷新。完成后可练习，不重复发放本周奖励。</p>{r.cleared.length===r.bosses.length&&(confirm?<div className="action-row"><Button disabled={locked} onClick={()=>{setConfirm(false);send({type:'raidRestart'});}}>确认开始练习远征</Button><Button variant="outline" onClick={()=>setConfirm(false)}>取消</Button></div>:<Button variant="outline" disabled={locked} onClick={()=>setConfirm(true)}>重新挑战完整副本</Button>)}</footer>
 </div>;
}
