'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {GameSelect,GameSelectOption} from '@/components/ui/game-select';
import type {GameProps} from './game-ui';
import {duration} from './game-ui';
import './raid-command.css';
const roleNames:Record<string,string>={tank:'坦克',healer:'治疗',melee:'近战',ranged:'远程'};
function Choice({label,value,onChange,options,disabled=false}:any){return <label className="raid-choice"><span>{label}</span><GameSelect aria-label={label} value={value} onValueChange={onChange} disabled={disabled}>{options.map((o:any)=><GameSelectOption key={o.id} value={o.id}>{o.name}</GameSelectOption>)}</GameSelect></label>;}
export function RaidLiveOrders({state:s,data:d,busy,send}:GameProps){
 const r=d.raidCommand;if(!r?.live||!s.combat)return null;
 const order=(key:string)=>send({type:'raidOrder',order:key,encounterId:r.live.encounterId});
 return <section className="raid-live-orders" aria-label="团长战中指挥"><div className="action-row"><b>团长口令</b><Button size="sm" variant="outline" disabled={busy||s.clock<r.live.focusReadyAt} onClick={()=>order(r.live.focusAdds?'focusBoss':'focusAdds')}>{r.live.focusAdds?'当前清怪 → 转火首领':'当前首领 → 转火小怪'}</Button>{r.cooldowns.map((c:any)=><Button size="sm" key={c.id} variant="outline" title={c.reason||c.hint} disabled={busy||!!c.reason} onClick={()=>order(c.id)}>{c.name} · {c.reason||(c.trigger==='manual'?'待口令':'条件触发')}{c.remaining>0?` ${duration(c.remaining)}`:''}</Button>)}</div><small>预留技能由已安排成员执行，并中断其当前读条；受真实距离、资源和冷却限制。切换集火会影响输出目标。</small>{r.live.events.length>0&&<p role="status">{r.live.events.at(-1).text}</p>}</section>;
}
function Preparation({bossId,info,props}:{bossId:string;info:any;props:GameProps}){
 const {data:d,busy,send}=props,r=d.raidCommand;
 const [plan,setPlan]=useState(()=>structuredClone(info.plan)),[saved,setSaved]=useState(false);
 const change=(key:string,value:any)=>{setPlan((p:any)=>({...p,[key]:value}));setSaved(false);};
 const dirty=JSON.stringify(plan)!==JSON.stringify(info.plan);
 const locked=busy||r.locked,tanks=r.members.filter((m:any)=>m.role==='tank'),last=r.attempts.filter((a:any)=>a.bossId===bossId).at(-1);
 const assign=(job:string,index:number,id:string)=>{const ids=[...(plan.jobs[job]||[])];ids[index]=id==='none'?'':id;change('jobs',{...plan.jobs,[job]:ids.filter(Boolean)});};
 return <div className="raid-preparation"><div className="raid-plan-grid">
 <Choice label="主坦 · 首领" value={plan.mainTank} options={tanks} disabled={locked} onChange={(v:string)=>{setPlan((p:any)=>({...p,mainTank:v,offTank:p.offTank===v?p.mainTank:p.offTank,cooldowns:{...p.cooldowns,wall:{...p.cooldowns.wall,actorId:r.cooldowns.find((c:any)=>c.id==='wall').candidates.some((c:any)=>c.id===v)?v:''}}}));}}/>
 <Choice label="副坦 · 小怪" value={plan.offTank} options={tanks.filter((m:any)=>m.id!==plan.mainTank)} disabled={locked} onChange={(v:string)=>change('offTank',v)}/>
 <Choice label="默认集火" value={plan.focus} options={[{id:'adds',name:'先清小怪 · 降低场面压力'},{id:'boss',name:'集中首领 · 副坦牵制小怪'}]} disabled={locked} onChange={(v:string)=>change('focus',v)}/>
 <Choice label="开场站位" value={plan.formation} options={[{id:'spread',name:'分散 · 减少爆炸波及'},{id:'compact',name:'紧凑 · 更易覆盖治疗'}]} disabled={locked} onChange={(v:string)=>change('formation',v)}/>
 <Choice label="火区躲避纪律" value={plan.movement} options={[{id:'early',name:'提前撤离 · 取消当前读条'},{id:'finishCast',name:'贪读条 · 落地前继续施法'}]} disabled={locked} onChange={(v:string)=>change('movement',v)}/>
 <Choice label="驱散调度" value={plan.dispelPolicy} options={[{id:'assigned',name:'专人分区 · 保留其余成员读条'},{id:'all',name:'全员协助 · 牺牲治疗与输出时间'}]} disabled={locked} onChange={(v:string)=>change('dispelPolicy',v)}/>
 </div><details className="raid-assignment-details"><summary>机制分工 · 指定负责人和接替成员（{Object.values(plan.jobs).filter((ids:any)=>ids.length).length}项已安排）</summary><p>两名驱散者优先覆盖不同小队，再协助其他队。宁神与防恐由名单中的成员按可用状态接替。专人模式下，未指派成员不会自动兜底。</p><div className="raid-plan-grid">{r.jobs.map((j:any)=><fieldset key={j.id}><legend>{j.name}</legend>{[0,1].map(index=><Choice key={index} label={`${j.name} · ${index?'接替':'负责'}`} value={plan.jobs[j.id][index]||'none'} disabled={locked} options={[{id:'none',name:'不安排'},...j.candidates.filter((c:any)=>!plan.jobs[j.id].includes(c.id)||plan.jobs[j.id][index]===c.id)]} onChange={(v:string)=>assign(j.id,index,v)}/>)}{!j.candidates.length&&<small>当前团队无人掌握此技能，需要调整阵容。</small>}</fieldset>)}</div></details>
 <details className="raid-assignment-details"><summary>关键技能 · 预留真实职业冷却（{Object.values(plan.cooldowns).filter((slot:any)=>slot.actorId).length}项已预留）</summary><div className="raid-plan-grid">{r.cooldowns.map((c:any)=><fieldset key={c.id}><legend>{c.name}</legend><p>{c.hint}</p><Choice label={`${c.name}负责人`} value={plan.cooldowns[c.id].actorId||'none'} options={[{id:'none',name:'不预留'},...c.candidates.filter((m:any)=>c.id!=='wall'||m.id===plan.mainTank)]} disabled={locked} onChange={(v:string)=>change('cooldowns',{...plan.cooldowns,[c.id]:{...plan.cooldowns[c.id],actorId:v==='none'?'':v}})}/><Choice label={`${c.name}执行时机`} value={plan.cooldowns[c.id].trigger} options={[{id:'automatic',name:'按血量 / 法力阈值自动执行'},...(c.id==='wall'&&bossId==='magmadar'?[{id:'frenzy',name:'首领狂暴时开启'},{id:'fear',name:'玛格曼达恐慌前2秒'}]:[]),{id:'manual',name:'等待团长口令'}]} disabled={locked} onChange={(v:string)=>change('cooldowns',{...plan.cooldowns,[c.id]:{...plan.cooldowns[c.id],trigger:v}})}/></fieldset>)}</div></details>
 <div className="action-row"><Button disabled={locked} onClick={async()=>{if(await send({type:'raidPlan',bossId,plan}))setSaved(true);}}>发布战前指挥</Button>{last&&<Button variant="outline" disabled={locked} onClick={()=>{setPlan((p:any)=>({...p,movement:last.review.failures.fire?'early':p.movement,formation:last.review.failures.fire?'spread':p.formation,dispelPolicy:last.review.failures.doom?'all':p.dispelPolicy,cooldowns:Object.fromEntries(Object.entries(p.cooldowns).map(([k,v]:any)=>[k,{...v,trigger:'automatic'}]))}));setSaved(false);}}>根据上次复盘调整草案</Button>}<span role="status">{r.locked?'战斗、推进或休整期间不能修改战前安排。':dirty?'草案有修改，发布后生效。':saved||info.published?'已发布，下一次挑战执行此安排。':'尚未发布，当前展示建议安排。'}</span></div><p className="footnote">指挥按首领分别保存。发布后下次开战生效；未发布时使用建议安排。自动推进在首领前停步，留出检查与调整时间。</p></div>;
}
export default function RaidCommandPanel(props:GameProps){
 const {data:d}=props,r=d.raidCommand,g=d.goldRaid;
 const [selected,setSelected]=useState('');if(!r)return null;
 const bossId=selected||r.live?.bossId||(r.bosses.some((b:any)=>b.id===g.activeBoss)?g.activeBoss:'')||r.bosses.find((b:any)=>!g.cleared.includes(b.id))?.id||r.bosses[0].id;
 const boss=r.bosses.find((b:any)=>b.id===bossId)||r.bosses[0],info=r.plans[boss.id],attempts=r.attempts.filter((a:any)=>a.bossId===boss.id),last=attempts.at(-1),previous=attempts.at(-2);
 return <section className="panel raid-command-panel" aria-label="开荒指挥台"><div className="section-heading"><div><div className="eyebrow">PLAN / EXECUTE / LEARN</div><h2>开荒指挥台</h2></div><Choice label="作战首领" value={boss.id} onChange={setSelected} options={r.bosses}/></div><p>{boss.description}</p><RaidLiveOrders {...props}/>
 {last&&<section className="raid-debrief" aria-label="团灭与战斗复盘"><h3>{last.won?'击败首领 · 本次复盘':last.abandoned?'主动撤退 · 本次复盘':'挑战复盘 · 调整后再战'}</h3>{last.abandoned&&<p>本次由团长主动结束；撤退结算的倒下人数不代表自然死亡，不作为死因判断。</p>}<div className="raid-review-metrics"><span>首领剩余 <b>{last.review.bossRemaining}%</b></span><span>治疗平均剩余法力 <b>{last.review.healerMana}%</b></span><span>首个倒下 <b>{last.review.firstDeath?`${last.review.firstDeath.name} · ${roleNames[last.review.firstDeath.role]} · ${last.review.firstDeath.cause}`:'无记录'}</b></span>{previous&&<span>上次首领剩余 <b>{previous.review.bossRemaining}%</b></span>}</div><ul>{last.review.suggestions.map((text:string)=><li key={text}>{text}</li>)}</ul>{last.review.unused.length>0&&<p>预留但未使用：{last.review.unused.join('、')}。检查触发条件和施法者状态，未使用不一定代表失误。</p>}<details><summary>本次执行记录与战前安排</summary><p>{last.review.plan.focus==='adds'?'先清小怪':'集中首领'} / {last.review.plan.formation==='spread'?'分散':'紧凑'} / {last.review.plan.movement==='early'?'提前撤离':'贪读条'} / {last.review.plan.dispelPolicy==='assigned'?'专人驱散':'全员驱散'}</p>{last.review.events.length?last.review.events.map((e:any,i:number)=><p key={i}>{e.text}</p>):<p>本次没有成功执行的团长口令或预留技能。</p>}</details></section>}
 <details open={!r.live} className="raid-preparation-fold"><summary>战前作战安排 · {boss.name}</summary><Preparation key={boss.id+JSON.stringify(info.plan)} bossId={boss.id} info={info} props={props}/></details></section>;
}
