"use client";
import {GameSelect,GameSelectOption} from '@/components/ui/game-select';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {GameProps,Icon,money,duration} from './game-ui';
import './economy.css';
import BatchTrade from './batch-trade';
import type {InventoryItem,MarketItem,AuctionListing,MarketRecord} from './economy-types';

export function Bank({state:s,data:d,busy,send}:GameProps){
 const [search,setSearch]=useState(''),[count,setCount]=useState(1);
 const locked=busy||!d.bankHere||!!s.combat||!!s.dungeon||!['idle','hunt'].includes(s.activity.type),valid=Number.isInteger(count)&&count>0;
 const rows=(list:InventoryItem[],deposit:boolean)=><div className="storage-list">{list.filter(i=>d.items[i.id]?.name.includes(search)).map(i=><div className="storage-row" key={i.uid}><Icon src={d.items[i.id]?.icon} name={d.items[i.id]?.name||'物品'}/><div className="grow"><strong className={'rarity-'+d.items[i.id]?.quality}>{d.items[i.id]?.name} ×{i.count}</strong><small>{i.locked?'🔒 已锁定 · ':''}{i.bound?'已绑定 · ':''}{d.enchants[i.enchant||'']?.description||''}</small></div><Button size="sm" variant="outline" disabled={locked||!valid||count>i.count||deposit&&!d.inventoryActions[i.uid]?.bankable} onClick={()=>send({type:deposit?'bankDeposit':'bankWithdraw',uid:i.uid,count})}>{deposit?'存入':'取出'} {valid?count:''}</Button><Button size="sm" variant="ghost" disabled={locked||deposit&&!d.inventoryActions[i.uid]?.bankable} onClick={()=>send({type:deposit?'bankDeposit':'bankWithdraw',uid:i.uid,count:i.count})}>整组</Button></div>)}{!list.length&&<p className="empty">这里还没有物品。</p>}</div>;
 return <section className="panel"><div className="section-heading"><div><div className="eyebrow">个人仓储</div><h2>银行 <small>{s.bank.length} / {d.bankCapacity} 格</small></h2></div><Button variant="outline" disabled={locked||!d.bankUpgradeCost||s.money<d.bankUpgradeCost} onClick={()=>send({type:'expandBank'})}>{d.bankUpgradeCost?'扩展 16 格 · '+money(d.bankUpgradeCost):'容量已满'}</Button></div><p>{d.bankHere?'你在银行附近，可以办理存取。':'银行位于暴风城贸易区与铁炉堡；当前可以查看库存。'}装备的附魔、绑定、耐久和锁定状态会保留。</p>{!d.bankHere&&<Button variant="outline" disabled={busy||!!s.combat||!!s.dungeon||!['idle','hunt'].includes(s.activity.type)} onClick={()=>send({type:'travel',to:'stormwind'})}>前往暴风城银行</Button>}<div className="economy-toolbar"><input aria-label="搜索银行物品" placeholder="搜索物品…" value={search} onChange={e=>setSearch(e.target.value)}/><label>每次数量 <input aria-label="存取数量" type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))}/></label><Button variant="outline" disabled={locked} onClick={()=>send({type:'bankDepositMaterials'})}>材料一键存入</Button><Button variant="outline" disabled={locked} onClick={()=>send({type:'sortBank'})}>整理银行</Button></div><div className="storage-columns"><section><h3>随身背包 · {s.bag.length}/{d.bagCapacity}</h3>{rows(s.bag,true)}</section><section><h3>银行库存 · {s.bank.length}/{d.bankCapacity}</h3>{rows(s.bank,false)}</section></div></section>;
}

export function Auction({state:s,data:d,busy,send}:GameProps){
 const [mode,setMode]=useState('购买'),[search,setSearch]=useState(''),[category,setCategory]=useState('全部'),[count,setCount]=useState(1),[page,setPage]=useState(0);
 const locked=busy||!!s.combat||!!s.dungeon||!['idle','hunt'].includes(s.activity.type),valid=Number.isInteger(count)&&count>=1&&count<=100;
 const market=d.market.filter((r:MarketItem)=>d.items[r.id]?.name.includes(search)&&(category==='全部'||category==='附魔羊皮纸'&&r.enchant||category==='材料'&&d.items[r.id]?.class===7||category==='成品'&&d.items[r.id]?.class!==7&&!r.enchant));
 const pages=Math.max(1,Math.ceil(market.length/36)),current=Math.min(page,pages-1);
 const sellable=s.bag.filter((i:InventoryItem)=>d.inventoryActions[i.uid]?.tradable&&d.items[i.id]?.quality<=3),gross=sellable.reduce((n:number,i:InventoryItem)=>n+Math.floor(d.inventoryActions[i.uid].quote.sell*i.count*.95),0);
 return <section className="panel"><div className="section-heading"><div><div className="eyebrow">远程交易 · 模拟市场</div><h2>拍卖行</h2></div><span className="wallet">{money(s.money)}</span></div><p>系统按固定参考价供货与收购。上架后 30 秒自动成交，收取 5% 手续费；价格与预计到账均提前显示。离线也按游戏时间结算。</p><div className="filterbar">{['购买','上架物品','我的拍卖','成交记录'].map(t=><button className={mode===t?'active':''} onClick={()=>setMode(t)} key={t}>{t}{t==='我的拍卖'&&s.auctions.length>0?' · '+s.auctions.length:''}</button>)}</div>
 {mode==='购买'&&<><div className="economy-toolbar"><input aria-label="搜索拍卖商品" placeholder="搜索材料、药水、附魔…" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><GameSelect aria-label="拍卖商品分类" value={category} onValueChange={nextValue=>{setCategory(nextValue);setPage(0);}}>{['全部','材料','成品','附魔羊皮纸'].map(t=><GameSelectOption value={t} key={t}>{t}</GameSelectOption>)}</GameSelect><label>购买数量 <input aria-label="购买数量" type="number" min={1} max={100} value={count} onChange={e=>setCount(Number(e.target.value))}/></label></div><div className="economy-toolbar recipe-pagination"><small>共 {market.length} 件商品 · 第 {current+1} / {pages} 页</small><Button size="sm" variant="outline" disabled={current===0} onClick={()=>setPage(current-1)}>上一页</Button><Button size="sm" variant="outline" disabled={current>=pages-1} onClick={()=>setPage(current+1)}>下一页</Button></div><div className="market-grid">{market.slice(current*36,(current+1)*36).map((r:MarketItem)=><article className="market-card" key={r.id}><div className="recipe-title"><Icon src={d.items[r.id]?.icon} name={d.items[r.id]?.name||'物品'}/><div><h3>{d.items[r.id]?.name}</h3><small>{money(r.buy)} / 个</small></div></div>{d.items[r.id]?.description&&<p className="enchant-text">{d.items[r.id].description}</p>}<Button size="sm" variant="outline" disabled={locked||!valid||s.money<r.buy*count} onClick={()=>send({type:'auctionBuy',id:r.id,count})}>购买 ×{valid?count:'—'} · {money(valid?r.buy*count:0)}</Button></article>)}</div>{!market.length&&<p className="empty">没有匹配的商品。</p>}</>}
 {mode==='上架物品'&&<><div className="economy-callout"><p>一键上架未锁定、未绑定的白色、绿色和蓝色物品；也可在下方自行勾选物品批量上架。</p><Button disabled={locked||!sellable.length||s.auctions.length+sellable.length>100} onClick={()=>send({type:'auctionSellAll'})}>全部快捷上架 · {sellable.length} 组 · 预计 {money(gross)}</Button></div><BatchTrade key={s.id} state={s} data={d} busy={locked} send={send} auction/></>}
 {mode==='我的拍卖'&&<>{s.auctions.map((a:AuctionListing)=><div className="storage-row" key={a.id}><div className="grow"><strong>{d.items[a.item.id]?.name} ×{a.item.count}</strong><small>{duration(a.endsAt-s.clock)} 后成交 · 预计到账 {money(a.net)}</small></div><Button size="sm" variant="outline" disabled={locked} onClick={()=>send({type:'auctionCancel',id:a.id})}>撤回背包</Button></div>)}{!s.auctions.length&&<p className="empty">暂无正在出售的物品。</p>}</>}
 {mode==='成交记录'&&<>{s.marketHistory.map((a:MarketRecord)=><div className="storage-row" key={a.id}><span className="grow">{d.items[a.item]?.name||'物品'} ×{a.count}</span><strong>+ {money(a.net)}</strong></div>)}{!s.marketHistory.length&&<p className="empty">成交后会在这里保留最近 30 条记录。</p>}</>}
 </section>;
}
