import {seedCompanion} from './support/characters.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {MemoryStore} from '../../persistence/src/memory.ts';
import {GameService} from '../src/service.ts';
import type {Instance,Character,Rules} from '../src/model.ts';

async function fixture(){const store=new MemoryStore();let now=1000;const service=new GameService(store,{contentVersion:'test',now:()=>now,seed:()=>123});const leader=(await service.createAccount('a',{name:'Leader',classId:8,raceId:1},'create')).account.primaryCharacterId;const guest=(await service.createAccount('b',{name:'Guest',classId:8,raceId:1},'create')).account.primaryCharacterId;const instanceId=(await service.command('a',{type:'createInstance',requestId:'form'})).instanceId!;await service.command('b',{type:'joinInstance',instanceId,requestId:'join'});await service.command('a',{type:'startInstance',instanceId,requestId:'start'});await store.transaction(async tx=>{const instance=(await tx.get<Instance>('instances',instanceId))!;instance.simulation!.combat.enemies[0].position=20;await tx.put('instances',instance);});return{store,service,leader,guest,instanceId,time:(value:number)=>{now=value;},instance:()=>store.transaction(tx=>tx.get<Instance>('instances',instanceId))};}
test('only the leader can abandon a shared battle and retries cannot repeat the death or rewards',async()=>{
 const f=await fixture(),before=(await f.instance())!,encounterId=before.simulation!.combat.id;
 assert.equal((await f.service.snapshot('a')).instance!.leaderId,f.leader);
 await assert.rejects(f.service.command('b',{type:'abandonCombat',encounterId,requestId:'guest-abandon'}),error=>(error as any).code==='VISITOR_COMMAND');
 assert.deepEqual(await f.instance(),before);
 const command={type:'abandonCombat',encounterId,requestId:'leader-abandon'};
 await f.service.command('a',command);const after=(await f.instance())!;
 assert.equal(after.simulation!.combat,null);assert.ok([after.simulation!,...after.simulation!.party].every((c:Rules)=>c.hp===0));
 assert.equal(after.sequence,before.sequence+1);assert.equal(after.simulation!.totals.deaths,before.simulation!.totals.deaths+1);
 await f.service.command('a',command);assert.deepEqual(await f.instance(),after);
 for(const account of ['a','b']){const snapshot=await f.service.snapshot(account);assert.equal(snapshot.state.hp,0);assert.equal(snapshot.state.combat,null);}
 await f.service.command('a',{type:'revive',requestId:'revive'});f.time(11000);await f.service.work(11000);
 assert.ok([(await f.instance())!.simulation!,...(await f.instance())!.simulation!.party].every((c:Rules)=>c.hp>0));
});
test('visitor manual cast spends only its own mana and retains the shared leader root and rules',async()=>{const f=await fixture(),before=(await f.instance())!.simulation!,enemy=before.combat.enemies[0].id,guest=before.party.find((c:Rules)=>c.id===f.guest);await f.service.command('b',{type:'cast',id:133,target:enemy,requestId:'cast'});const after=(await f.instance())!.simulation!,caster=after.party.find((c:Rules)=>c.id===f.guest);assert.equal(after.id,f.leader);assert.equal(after.mana,before.mana);assert.deepEqual(after.bag,before.bag);assert.equal(after.cast,before.cast);assert.equal(caster.mana,guest.mana);assert.ok(caster.cast.timing.cost>0);assert.equal(caster.cast.timing.committed,false);assert.equal(caster.cast.spell,133);assert.equal(caster.cast.target,enemy);assert.deepEqual(caster.rules,guest.rules);assert.deepEqual(caster.learned,guest.learned);assert.equal(after.logs.at(-1).actorId,f.guest);
 await f.service.command('b',{type:'cast',id:133,target:enemy,requestId:'cast'});assert.equal((await f.instance())!.simulation!.party.find((c:Rules)=>c.id===f.guest).mana,caster.mana);
});
test('visitor cannot spoof caster, control leader settings or target another account',async()=>{const f=await fixture(),before=await f.instance();for(const [i,command]of [{type:'cast',id:133,target:f.leader},{type:'cast',id:133,casterId:f.leader,target:'enemy-0'},{type:'settings',target:f.leader,health:90,mana:80},{type:'petCommand',actorId:f.leader,command:'aggressive'}].entries())await assert.rejects(f.service.command('b',{...command,requestId:`bad-${i}`}),error=>(error as any).code==='FORBIDDEN');assert.deepEqual(await f.instance(),before);await assert.rejects(f.service.command('b',{type:'cast',id:116,target:'enemy-0',requestId:'untrained'}),/尚未学习/);await assert.rejects(f.service.command('b',{type:'cast',id:1459,target:f.guest,requestId:'unsupported'}),/当前手动战斗施法支持/);});
test('visitor settings and pet posture affect only its own unit; inventory pet operations are explicit unsupported',async()=>{const f=await fixture();await f.store.transaction(async tx=>{const instance=(await tx.get<Instance>('instances',f.instanceId))!;instance.simulation!.pet={id:'leader-pet',kind:'imp',hp:10,petUnit:true,mode:'passive'};instance.simulation!.party.find((c:Rules)=>c.id===f.guest).pet={id:'guest-pet',kind:'imp',hp:10,petUnit:true,mode:'passive'};await tx.put('instances',instance);});const before=(await f.instance())!.simulation!;await f.service.command('b',{type:'settings',health:90,mana:80,requestId:'settings'});await f.service.command('b',{type:'petCommand',command:'aggressive',requestId:'pet'});const after=(await f.instance())!.simulation!,guest=after.party.find((c:Rules)=>c.id===f.guest);assert.deepEqual(after.settings,before.settings);assert.equal(after.pet.mode,'passive');assert.equal(guest.settings.health,90);assert.equal(guest.settings.mana,80);assert.equal(guest.pet.mode,'aggressive');await assert.rejects(f.service.command('b',{type:'petCommand',command:'feed',itemId:117,requestId:'feed'}),/仅支持/);});
test('instance roster validation reports domain errors for malformed input without partial locks',async()=>{const store=new MemoryStore(),service=new GameService(store,{contentVersion:'test',now:()=>1000});const hero=(await service.createAccount('a',{name:'Hero',classId:8,raceId:1},'create')).account.primaryCharacterId;const malformed:unknown[]=[null,{},'hero',[],[1],[hero,hero],['']];for(const [i,characterIds]of malformed.entries())await assert.rejects(service.command('a',{type:'createInstance',characterIds,requestId:`bad-${i}`}),error=>(error as any).code==='ROSTER'&&(error as any).status===400);assert.equal((await store.transaction(tx=>tx.list('instances'))).length,0);assert.equal((await store.transaction(tx=>tx.list('actor_leases'))).length,0);await assert.rejects(service.command('a',{type:'createInstance',contentId:'toString',requestId:'prototype'}),error=>(error as any).code==='CONTENT');});
test('leader account cannot leave through a companion while another account remains',async()=>{const store=new MemoryStore(),service=new GameService(store,{contentVersion:'test',now:()=>1000});const hero=(await service.createAccount('a',{name:'Hero',classId:8,raceId:1},'create')).account.primaryCharacterId;await service.createAccount('b',{name:'Guest',classId:8,raceId:1},'create');const added=await seedCompanion(service,'a',{type:'createCompanion',name:'Helper',classId:8,raceId:1,requestId:'helper'}),helper=added.roster.find(c=>c.name==='Helper')!.id;const instanceId=(await service.command('a',{type:'createInstance',characterIds:[hero,helper],requestId:'form'})).instanceId!;await service.command('b',{type:'joinInstance',instanceId,requestId:'join'});const before=await store.transaction(tx=>tx.get('instances',instanceId));await assert.rejects(service.command('a',{type:'leaveInstance',characterId:helper,instanceId,requestId:'leave'}),error=>(error as any).code==='LEADER');assert.deepEqual(await store.transaction(tx=>tx.get('instances',instanceId)),before);assert.equal((await store.transaction(tx=>tx.list('actor_leases'))).length,3);});
test('departing account removes its actors from both roster and completed simulation',async()=>{const store=new MemoryStore();let now=1000;const service=new GameService(store,{contentVersion:'test',now:()=>now,seed:()=>123});await service.createAccount('a',{name:'Hero',classId:8,raceId:1},'create');const guest=(await service.createAccount('b',{name:'Guest',classId:8,raceId:1},'create')).account.primaryCharacterId;await store.transaction(async tx=>{const wallet=(await tx.get<Rules & {id:string}>('wallets',guest))!;wallet.balance=1000;await tx.put('wallets',wallet);});const instanceId=(await service.command('a',{type:'createInstance',requestId:'form'})).instanceId!;await service.command('b',{type:'joinInstance',instanceId,requestId:'join'});await service.command('a',{type:'startInstance',instanceId,requestId:'start'});now=61000;await service.work(now);const before=(await store.transaction(tx=>tx.get<Instance>('instances',instanceId)))!;assert.equal(before.simulation!.combat,null);const departing=before.roster.filter(r=>r.accountId==='b').map(r=>r.characterId);assert.equal(departing.length,1);await service.command('b',{type:'leaveInstance',instanceId,requestId:'leave'});const after=(await store.transaction(tx=>tx.get<Instance>('instances',instanceId)))!;assert.ok(after.roster.every(r=>r.accountId!=='b'));assert.ok(after.simulation!.party.every((unit:Rules)=>!departing.includes(unit.id)));});
