import {seedCompanion} from './support/characters.ts';
import test from 'node:test';
import assert from 'node:assert/strict';
import {MemoryStore} from '../../persistence/src/memory.ts';
import {GameService} from '../src/service.ts';
import type {Character,Rules,Activity,Instance} from '../src/model.ts';

async function fixture(){const store=new MemoryStore();let now=1000,n=0;const service=new GameService(store,{contentVersion:'test-v1',now:()=>now,id:()=>`id-${++n}`,seed:()=>12345});const snapshot=await service.createAccount('a',{name:'Hero',classId:8,raceId:1},'create');return{store,service,hero:snapshot.account.primaryCharacterId,time:(value:number)=>{now=value;}};}
async function edit(store:MemoryStore,id:string,patch:Rules){await store.transaction(async tx=>{const c=(await tx.get<Character>('characters',id))!;Object.assign(c.rules,patch);await tx.put('characters',c);});}
async function material(store:MemoryStore,owner:string,item:number,count:number){await store.transaction(tx=>tx.insert('items',{id:`material:${owner}:${item}`,accountId:'a',ownerCharacterId:owner,container:'bag',position:100,data:{id:item,count,durability:0,bound:false},source:'fixture'}));}
async function companion(f:Awaited<ReturnType<typeof fixture>>,name='Helper'){const result=await seedCompanion(f.service,'a',{type:'createCompanion',name,classId:8,raceId:1,requestId:name});return result.roster.find(c=>c.name===name)!.id;}
test('normalized rows and stable IDs; receipts reject changed payload',async()=>{const f=await fixture();const state=await f.service.snapshot('a');assert.equal(state.state.id,f.hero);const c=await f.store.transaction(tx=>tx.get<Character>('characters',f.hero));for(const field of ['bag','money','party','dungeon','activity'])assert.equal(c!.rules[field],undefined);assert.equal((await f.store.transaction(tx=>tx.list('items'))).length>0,true);await assert.rejects(f.service.createAccount('a',{name:'Other',classId:8,raceId:1},'create'),/requestId/);});
test('two workers compete for shared materials atomically; durable craft survives restart',async()=>{const f=await fixture(),other=await companion(f);await edit(f.store,f.hero,{professions:{firstaid:{skill:1,cap:75}}});await edit(f.store,other,{professions:{firstaid:{skill:1,cap:75}}});await material(f.store,f.hero,2589,1);const commands=[f.hero,other].map((characterId,n)=>f.service.command('a',{type:'craft',characterId,payerId:f.hero,recipientId:other,id:'spell-3275',count:1,requestId:`craft-${n}`}));const results=await Promise.allSettled(commands);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal((await f.store.transaction(tx=>tx.list('reservations'))).length,1);f.time(4000);const restarted=new GameService(f.store,{contentVersion:'test-v1',now:()=>4000,seed:()=>9876});assert.deepEqual((await restarted.work()).errors,[]);await restarted.work();const produced=(await restarted.snapshot('a',other)).state.bag.filter((i:Rules)=>i.id===1251);assert.equal(produced.reduce((n:number,i:Rules)=>n+i.count,0),1);assert.equal((await f.store.transaction(tx=>tx.list('actor_leases'))).length,0);});
test('rejected craft rolls back every durable table',async()=>{const f=await fixture();await edit(f.store,f.hero,{professions:{firstaid:{skill:1,cap:75}}});await assert.rejects(f.service.command('a',{type:'craft',id:'spell-3275',count:1,requestId:'bad'}));assert.equal((await f.store.transaction(tx=>tx.list('activities'))).length,0);assert.equal((await f.store.transaction(tx=>tx.list('reservations'))).length,0);assert.equal((await f.store.transaction(tx=>tx.list('actor_leases'))).length,0);});
test('gather random stream independent; recall preserves settled gains and releases only after return',async()=>{const f=await fixture(),other=await companion(f);for(const id of [f.hero,other])await edit(f.store,id,{location:'northwood',professions:{herbalism:{skill:1,cap:75}}});await f.service.command('a',{type:'gatherAll',characterId:f.hero,requestId:'g1'});await f.service.command('a',{type:'gatherAll',characterId:other,requestId:'g2'});f.time(4000);assert.deepEqual((await f.service.work()).errors,[]);const left=await f.service.snapshot('a',f.hero),right=await f.service.snapshot('a',other);assert.equal(left.state.bag.find((i:Rules)=>i.id===2447).count,right.state.bag.find((i:Rules)=>i.id===2447).count);const activity=left.activities.find(a=>a.actorId===f.hero)!;assert.equal(activity.status,'running');await f.service.command('a',{type:'recall',activityId:activity.id,requestId:'recall'});assert.ok(await f.store.transaction(tx=>tx.get('actor_leases',f.hero)));f.time(7000);assert.deepEqual((await f.service.work()).errors,[]);assert.equal(await f.store.transaction(tx=>tx.get('actor_leases',f.hero)),null);assert.equal((await f.service.snapshot('a')).state.bag.find((i:Rules)=>i.id===2447).count,left.state.bag.find((i:Rules)=>i.id===2447).count);});
test('major profession cap and individual reward settlement idempotency',async()=>{const f=await fixture();await edit(f.store,f.hero,{location:'goldshire',professions:{herbalism:{skill:1,cap:75},mining:{skill:1,cap:75}}});await f.store.transaction(tx=>tx.put('wallets',{id:f.hero,characterId:f.hero,accountId:'a',balance:10000}));await assert.rejects(f.service.command('a',{type:'learnProfession',id:'alchemy',requestId:'third'}),/两个/);await edit(f.store,f.hero,{location:'northshire'});await f.service.command('a',{type:'accept',id:783,requestId:'accept'});const done=await f.service.command('a',{type:'turnin',id:783,requestId:'turnin'});await f.service.command('a',{type:'turnin',id:783,requestId:'new-retry'});assert.equal((await f.service.snapshot('a')).state.money,done.state.money);assert.equal((await f.store.transaction(tx=>tx.list('reward_claims'))).length,1);});
test('cross-account join needs ownership, all instance participants locked, fenced writer rejects stale epoch',async()=>{const f=await fixture();const b=await f.service.createAccount('b',{name:'Guest',classId:1,raceId:1},'create');const own=await f.service.command('a',{type:'createInstance',capacity:10,requestId:'instance'});const id=own.instanceId!;await assert.rejects(f.service.command('b',{type:'joinInstance',instanceId:id,characterIds:[f.hero],requestId:'steal'}),/不属于/);await f.service.command('b',{type:'joinInstance',instanceId:id,requestId:'join'});assert.equal((await f.service.snapshot('b')).instanceId,id);await assert.rejects(f.service.command('a',{type:'gatherAll',requestId:'busy'}));await f.service.command('a',{type:'startInstance',instanceId:id,requestId:'start'});const first=await f.service.acquireInstanceLease(id,'old',1000,1000);const replacement=await f.service.acquireInstanceLease(id,'new',2001,1000);assert.ok(replacement.epoch>first.epoch);await assert.rejects(f.service.advanceInstance(id,'old',first.epoch,2100),/失效/);assert.equal(await f.service.advanceInstance(id,'new',replacement.epoch,2100),true);await assert.rejects(f.service.command('b',{type:'strategy',target:f.hero,rules:[],requestId:'foreign'}),/自己角色/);assert.equal((await f.service.snapshot('b',b.account.primaryCharacterId)).instance!.sequence,(await f.service.snapshot('a')).instance!.sequence);});
test('40-seat roster supported and mercenary charges use business key across request IDs',async()=>{const f=await fixture();await f.store.transaction(tx=>tx.put('wallets',{id:f.hero,characterId:f.hero,accountId:'a',balance:1000}));const instance=(await f.service.command('a',{type:'createInstance',capacity:40,requestId:'instance'})).instanceId!;await f.service.command('a',{type:'hireMercenary',instanceId:instance,templateId:'warrior',requestId:'hire1'});await f.service.command('a',{type:'hireMercenary',instanceId:instance,templateId:'warrior',requestId:'hire2'});assert.equal((await f.service.snapshot('a')).state.money,900);assert.equal((await f.store.transaction(tx=>tx.list('contracts'))).length,1);for(let i=0;i<38;i++){const id=await companion(f,`helper${i}`);await f.service.command('a',{type:'joinInstance',characterId:id,instanceId:instance,requestId:`join${i}`});}assert.equal((await f.service.snapshot('a')).instance!.roster.length,40);await assert.rejects(f.service.command('a',{type:'hireMercenary',instanceId:instance,templateId:'mage',requestId:'overflow'}),/不能雇佣/);});
test('outbox/inbox retries deduplicate economic event delivery',async()=>{const f=await fixture();await f.service.command('a',{type:'accept',id:783,requestId:'q'});let count=0;await f.service.deliverOutbox('test',async()=>{count++;});await f.service.deliverOutbox('test',async()=>{count++;});assert.equal(count,1);});
test('idle companion gathering keeps progressing while hero has an independent instance',async()=>{const f=await fixture(),helper=await companion(f);await edit(f.store,helper,{location:'northwood',professions:{herbalism:{skill:1,cap:75}}});await f.service.command('a',{type:'gatherResource',characterId:helper,id:'northwood:bloom',requestId:'gather'});const started=await f.service.command('a',{type:'createInstance',requestId:'instance'});await f.service.command('a',{type:'startInstance',instanceId:started.instanceId,requestId:'start'});f.time(4000);assert.deepEqual((await f.service.work()).errors,[]);assert.ok((await f.service.snapshot('a',helper)).state.bag.some((i:Rules)=>i.id===2447));assert.equal((await f.service.snapshot('a')).instanceId,started.instanceId);});
test('craft actor, payer, recipient separated; reservation cancel restores payer and real cooldown belongs to actor',async()=>{const f=await fixture(),actor=await companion(f,'Actor'),recipient=await companion(f,'Recipient');await edit(f.store,actor,{professions:{alchemy:{skill:225,cap:300}}});await material(f.store,f.hero,3575,2);await material(f.store,f.hero,9149,1);await f.service.command('a',{type:'craft',characterId:actor,payerId:f.hero,recipientId:recipient,id:'spell-11479',count:1,requestId:'transmute'});f.time(4000);assert.deepEqual((await f.service.work()).errors,[]);assert.ok((await f.service.snapshot('a',recipient)).state.bag.some((i:Rules)=>i.id===3577));const actorRow=(await f.store.transaction(tx=>tx.get<Character>('characters',actor)))!;assert.equal(actorRow.professionReadyAt['category-310'],86404000);assert.equal((await f.store.transaction(tx=>tx.get<Character>('characters',f.hero)))!.professionReadyAt['category-310'],undefined);await assert.rejects(f.service.command('a',{type:'craft',characterId:actor,payerId:f.hero,recipientId:recipient,id:'spell-11479',count:1,requestId:'early'}),/冷却/);
  // Resume a paused simulation at a later wall time: real-time cooldown is expired.
  f.time(86405000);await edit(f.store,actor,{wallAt:86405000});await edit(f.store,f.hero,{wallAt:86405000});await f.service.command('a',{type:'craft',characterId:actor,payerId:f.hero,recipientId:recipient,id:'spell-11479',count:1,requestId:'late'});const activity=(await f.service.snapshot('a',actor)).activities.find(a=>a.actorId===actor&&a.status==='running')!;await f.service.command('a',{type:'recall',activityId:activity.id,requestId:'cancel'});f.time(86408000);assert.deepEqual((await f.service.work()).errors,[]);assert.equal((await f.service.snapshot('a')).state.bag.find((i:Rules)=>i.id===3575).count,1);});
test('shared quest gives each eligible character equipment once, without multiplying currency or experience',async()=>{const f=await fixture(),helper=await companion(f);await f.service.command('a',{type:'setParty',characterIds:[f.hero,helper],requestId:'party'});await edit(f.store,f.hero,{quests:{33:{kills:{299:8},event:false,acceptedAt:0,expiresAt:0}},completed:{7:1},location:'northshire'});await material(f.store,f.hero,750,8);const before=await f.service.snapshot('a',helper);const result=await f.service.command('a',{type:'turnin',id:33,choice:80,requestId:'reward'});const after=await f.service.snapshot('a',helper);assert.equal(after.state.xp,before.state.xp);assert.equal(after.state.money,before.state.money);assert.equal(after.state.bag.filter((i:Rules)=>i.id===80).length,1);await f.service.command('a',{type:'turnin',id:33,choice:80,requestId:'reward-again'});assert.equal((await f.service.snapshot('a',helper)).state.bag.filter((i:Rules)=>i.id===80).length,1);assert.equal((await f.store.transaction(tx=>tx.list<Rules>('reward_claims'))).filter(r=>r.questId===33&&r.rewardGroup==='equipment').length,2);assert.ok(result.state.completed[33]);});
test('two independent crafters cannot reserve the same payer material',async()=>{const f=await fixture(),first=await companion(f,'First'),second=await companion(f,'Second');for(const id of [first,second])await edit(f.store,id,{professions:{firstaid:{skill:1,cap:75}}});await material(f.store,f.hero,2589,1);const attempts=await Promise.allSettled([first,second].map(characterId=>f.service.command('a',{type:'craft',characterId,payerId:f.hero,id:'spell-3275',count:1,requestId:`craft:${characterId}`})));assert.equal(attempts.filter(r=>r.status==='fulfilled').length,1);assert.match((attempts.find(r=>r.status==='rejected') as PromiseRejectedResult).reason.message,/材料/);assert.equal((await f.store.transaction(tx=>tx.list('reservations'))).length,1);});
test('equipment transfer keeps unique identity and binding ownership on companion',async()=>{const f=await fixture(),helper=await companion(f);await f.service.command('a',{type:'setParty',characterIds:[f.hero,helper],requestId:'party'});await material(f.store,f.hero,80,1);const uid=`material:${f.hero}:80`;await f.service.command('a',{type:'equip',uid,target:helper,requestId:'equip'});const after=await f.service.snapshot('a',helper);assert.ok(Object.values(after.state.equipment).some((i:any)=>i.uid===uid));assert.equal((await f.store.transaction(tx=>tx.get<Rules>('items',uid)))!.ownerCharacterId,helper);assert.ok(!(await f.service.snapshot('a')).state.bag.some((i:Rules)=>i.uid===uid));});
test('completed shared encounter stops scheduled work and leaving releases actor lease',async()=>{const f=await fixture();const formed=await f.service.command('a',{type:'createInstance',requestId:'form'});await f.service.command('a',{type:'startInstance',instanceId:formed.instanceId,requestId:'start'});f.time(61000);assert.deepEqual((await f.service.work()).errors,[]);assert.equal((await f.service.snapshot('a')).instance!.status,'completed');assert.equal((await f.service.work()).instances,0);await f.service.command('a',{type:'leaveInstance',instanceId:formed.instanceId,requestId:'leave'});assert.equal((await f.service.snapshot('a')).instanceId,null);assert.equal(await f.store.transaction(tx=>tx.get('actor_leases',f.hero)),null);});

