import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {GameSelect,GameSelectOption} from '../../components/ui/game-select';
import '../../app/globals.css';
import './molten-core-demo.css';

const classes:Record<number,string>={1:'战',2:'圣',3:'猎',4:'贼',5:'牧',8:'法'};
const colors:Record<number,string>={1:'#c69b6d',2:'#f48cba',3:'#aad372',4:'#fff468',5:'#eeeeee',8:'#66d8ef'};
const roles:Record<string,string>={tank:'坦克',healer:'治疗',melee:'近战',ranged:'远程'};
const tacticLabels:Record<string,[string,string]>={focusAdds:['优先清理护卫','副坦牵制护卫，输出集火后转首领。'],dispel:['优先驱散末日与诅咒','牧师处理魔法，法师处理诅咒；消耗实际法力和公共冷却。'],tranquilize:['安排宁神射击','猎人保留宁神射击，应对玛格曼达的狂暴。'],fearWard:['保护主坦免受恐惧','矮人牧师轮流维持防护恐惧结界。'],avoidFire:['自动撤离火区','取消读条并移动，牺牲输出时间换取生存。']};
const seconds=(ms:number)=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
const percent=(value:number,max:number)=>Math.max(0,Math.min(100,Math.round(value/Math.max(1,max)*100)));
function App(){
 const [data,setData]=useState<any>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[selected,setSelected]=useState('mc-member-1'),[tab,setTab]=useState('damage'),[resetConfirm,setResetConfirm]=useState(false);
 const inFlight=useRef(false),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;let timer:ReturnType<typeof setTimeout>;
  const poll=async()=>{if(!inFlight.current){inFlight.current=true;try{const response=await fetch('/api/molten-core-demo');const payload=await response.json();if(!response.ok)throw new Error(payload.error);if(mounted.current){setData(payload);setError('');}}catch(e:any){if(mounted.current)setError(e.message);}finally{inFlight.current=false;}}
   if(mounted.current)timer=setTimeout(poll,500);
  };void poll();return()=>{mounted.current=false;clearTimeout(timer);};
 },[]);
 async function send(command:any){if(busy)return;setBusy(true);while(inFlight.current)await new Promise(resolve=>setTimeout(resolve,20));inFlight.current=true;try{const response=await fetch('/api/molten-core-demo',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});const payload=await response.json();if(!response.ok)throw new Error(payload.error);setData(payload);setError('');}catch(e:any){setError(e.message);}finally{setBusy(false);inFlight.current=false;}}
 if(!data)return <main className="mc-demo"><p role="status">{error||'正在集结公会远征队……'}</p></main>;
 const fighting=data.status==='combat',complete=data.status==='complete',active=data.bosses.find((b:any)=>b.id===data.activeBoss),unit=data.members.find((m:any)=>m.id===selected)||data.members[0],alive=data.members.filter((m:any)=>m.hp>0).length;
 const meter=[...data.meter].sort((a:any,b:any)=>(tab==='damage'?b.damage-a.damage:b.healing-a.healing)).slice(0,8),max=Math.max(1,...meter.map((m:any)=>tab==='damage'?m.damage:m.healing));
 const px=(x:number)=>70+(x+20)/70*860,py=(y:number)=>40+(y+25)/50*310;
 return <main className="mc-demo">
  <header className="mc-header"><div><p className="mc-eyebrow">BLACKROCK MOUNTAIN / GUILD EXPEDITION</p><h1>熔火之心 <span>25人远征</span></h1><p>60级核心小队＋20名公会战友 · 十首领战斗实验</p></div><div className="mc-progress"><b>{data.cleared.length}<small> / {data.bosses.length}</small></b><span>首领已击败</span></div></header>
  <p className="mc-demo-note">独立试玩 · 本作25人改编数值 · 预设60级蓝装队伍 · 进度仅保存在本机Demo，刷新可恢复</p>
  {error&&<p className="mc-error" role="alert">{error}</p>}
  <nav className="mc-route" aria-label="首领路线">{data.bosses.map((boss:any,i:number)=>{const cleared=data.cleared.includes(boss.id),locked=i>0&&!data.cleared.includes(data.bosses[i-1].id);return <section key={boss.id} className={`${cleared?'cleared':''} ${data.activeBoss===boss.id?'active':''}`}><span className="mc-boss-number">0{i+1}</span><div><h2>{boss.name}</h2><p>{boss.subtitle}</p><small>{cleared?'已击败':locked?'击败上一首领后解锁':fighting&&data.activeBoss===boss.id?'交战中':'可以挑战'}</small></div><button disabled={busy||fighting||locked||cleared} onClick={()=>void send({type:'start',bossId:boss.id})}>{cleared?'✓ 完成':locked?'未解锁':data.status==='defeat'&&data.activeBoss===boss.id?'重新挑战':'开始挑战'}</button></section>;})}</nav>
  <div className="mc-layout"><div className="mc-main">
  <section className="mc-battle"><div className="mc-section-heading"><div><span className="mc-eyebrow">{fighting?'ENCOUNTER IN PROGRESS':'EXPEDITION CAMP'}</span><h2>{complete?'熔火远征 · 全部首领已击败':active?active.name:'集结营地'}</h2></div><div className="mc-live"><span>{alive}/25 存活</span><b>{seconds(data.clock)}</b>{fighting&&<button disabled={busy} onClick={()=>void send({type:data.paused?'resume':'pause'})}>{data.paused?'继续演示':'暂停演示'}</button>}<GameSelect aria-label="演示速度" value={data.speed} onValueChange={value=>void send({type:'speed',speed:Number(value)})} disabled={busy}><GameSelectOption value={1}>1× 速度</GameSelectOption><GameSelectOption value={2}>2× 速度</GameSelectOption></GameSelect></div></div>
   {data.enemies.length>0&&<div className="mc-enemy-bars">{data.enemies.map((e:any)=><div key={e.id}><span>{e.name} {e.enraged&&<em>狂暴</em>}</span><small>{Math.ceil(e.hp).toLocaleString()} / {e.maxHp.toLocaleString()}</small><div className="mc-hp"><i style={{width:percent(e.hp,e.maxHp)+'%'}}/></div></div>)}</div>}
   <div className="mc-arena"><svg viewBox="0 0 1000 390" role="img" aria-label="实时战场：角色位置、首领与熔岩火区"><defs><radialGradient id="mc-floor"><stop stopColor="#4a3225"/><stop offset="1" stopColor="#171815"/></radialGradient><pattern id="mc-grid" width="60" height="45" patternUnits="userSpaceOnUse"><path d="M 60 0 L 0 0 0 45" fill="none" stroke="#c88c5410"/></pattern></defs><rect width="1000" height="390" fill="url(#mc-floor)"/><rect width="1000" height="390" fill="url(#mc-grid)"/><path d="M0 370 Q150 330 290 385 T550 370 T1000 360" fill="none" stroke="#d66a25" strokeWidth="5" opacity=".35"/>
    {data.fires.map((fire:any)=><g key={fire.id}><ellipse cx={px(fire.position)} cy={py(fire.positionY)} rx={fire.radius*860/70} ry={fire.radius*310/50} fill={data.clock>=fire.armedAt?'#e7543470':'#e77f2925'} stroke="#fc9a53" strokeDasharray={data.clock<fire.armedAt?'6 5':undefined}/><text x={px(fire.position)} y={py(fire.positionY)} textAnchor="middle" fill="#ffe0bf" fontSize="12">{data.clock<fire.armedAt?'即将爆炸':'熔岩'}</text></g>)}
    {data.enemies.filter((e:any)=>e.hp>0).map((e:any)=><g key={e.id}><path d={`M ${px(e.position)} ${py(e.positionY)-25} l 23 25 -23 25 -23 -25 Z`} fill={e.enraged?'#b24b32':'#5f322a'} stroke="#d89165" strokeWidth="2"/><text x={px(e.position)} y={py(e.positionY)+43} textAnchor="middle" fill="#edd4bc" fontSize="13">{e.name}</text></g>)}
    {data.members.map((m:any,i:number)=>{const x=fighting||active?px(m.position):135+(i%5)*70,y=fighting||active?py(m.positionY):65+Math.floor(i/5)*62;return <g key={m.id} opacity={m.hp>0?1:.3}><circle cx={x} cy={y} r={selected===m.id?17:13} fill="#1c211c" stroke={m.hp>0?colors[m.classId]:'#777'} strokeWidth={selected===m.id?3:1.5}/><text x={x} y={y+4} fill={colors[m.classId]} textAnchor="middle" fontSize="11">{m.hp>0?classes[m.classId]:'×'}</text><rect x={x-17} y={y+20} width={34*percent(m.hp,m.maxHp)/100} height="3" fill="#92c287"/>{m.cast&&<circle cx={x} cy={y} r="20" fill="none" stroke="#a0cbeb" strokeDasharray="3 5"/>}</g>;})}
    {!active&&<><text x="690" y="166" fill="#d1b480" fontSize="27" textAnchor="middle">黑石深处，远征将启</text><text x="690" y="202" fill="#aaa28d" fontSize="15" textAnchor="middle">检查战术，挑战第一名首领</text></>}
   </svg>{fighting&&data.paused&&<div className="mc-paused">演示已暂停 · 点击继续演示恢复</div>}</div>
   <div className="mc-mechanics">{fighting?data.nextMechanics.map((m:any)=><span key={m.name}>{m.name}<b>{Math.max(0,Math.ceil((m.at-data.clock)/1000))}秒</b></span>):<span>{active?.description||'2名坦克 · 5名治疗 · 18名输出。无需逐个操作，配置战术后由队友执行。'}</span>}</div>
   {fighting&&<div className="mc-battle-actions"><small>暂停与加速仅用于试玩；关闭后不离线推进。撤退按全员倒下结算。</small><button disabled={busy} onClick={()=>void send({type:'retreat'})}>撤退并重新整备</button></div>}
  </section>
  {['victory','defeat','complete'].includes(data.status)&&<section className={`mc-result ${data.status==='defeat'?'defeat':''}`} role="status"><h2>{complete?'远征完成':data.status==='victory'?'首领已击败':'本次挑战结束'}</h2><p>{data.status==='defeat'?'调整营地战术后可以重试，已击败的首领进度保留。':data.rewards.at(-1)?.name}</p><p>用时 {seconds(data.attempts.at(-1)?.duration||0)} · 倒下 {data.attempts.at(-1)?.deaths||0} 人 · 驱散 {data.support.dispels||0} 次 · 宁神 {data.support.tranquilizes||0} 次</p>{data.failures.doom>0&&<p>复盘：{data.failures.doom}次末日未及时驱散；检查驱散策略与治疗法力。</p>}{data.failures.fire>0&&<p>复盘：承受了{data.failures.fire}次火区伤害；保持自动撤离并观察恐惧重叠。</p>}</section>}
  <section className="mc-roster"><div className="mc-section-heading"><h2>公会成员</h2><span>选择成员查看配装与状态</span></div><div className="mc-squads">{data.squadNames.map((name:string,index:number)=><section key={name}><h3><small>0{index+1}</small>{name}</h3>{data.members.filter((m:any)=>m.squad===index).map((m:any)=><button className={`${m.id===selected?'selected':''} ${m.hp<=0?'dead':''}`} key={m.id} onClick={()=>setSelected(m.id)}><span className="mc-class" style={{color:colors[m.classId]}}>{classes[m.classId]}</span><div><span>{m.name}<small>{roles[m.role]}</small></span><div className="mc-member-hp"><i style={{width:percent(m.hp,m.maxHp)+'%'}}/></div><div className="mc-member-mana"><i style={{width:percent(m.mana,m.maxMana)+'%'}}/></div></div><b>{percent(m.hp,m.maxHp)}%</b></button>)}</section>)}</div><div className="mc-unit-detail"><strong style={{color:colors[unit.classId]}}>{unit.name}</strong><span>60级 · {roles[unit.role]}</span><span>生命 {Math.ceil(unit.hp)}/{unit.maxHp}</span>{unit.maxMana>0&&<span>法力 {Math.floor(unit.mana)}/{unit.maxMana}</span>}<span>{unit.hp<=0?'已倒下':unit.cast?`${unit.cast.name} · ${Math.max(0,(unit.cast.until-data.clock)/1000).toFixed(1)}秒`:'待命／自动行动'}</span>{unit.auras.filter((a:any)=>a.name!=='增益').map((a:any,i:number)=><em key={i}>{a.name}</em>)}</div><details><summary>查看{unit.name}的Demo配装</summary><p>{unit.equipment.map((e:any)=>e.name).join(' · ')}</p></details></section>
  </div><aside className="mc-sidebar">
   <section className="mc-tactics"><p className="mc-eyebrow">PREPARATION</p><h2>营地战术</h2><p>可故意关闭机制应对，比较战果。重试会补满生命、法力和弹药。</p>{Object.entries(tacticLabels).map(([key,[label,hint]])=><label key={key}><input type="checkbox" checked={data.tactics[key]} disabled={busy||fighting} onChange={e=>void send({type:'tactics',patch:{[key]:e.target.checked}})}/><span><b>{label}</b><small>{hint}</small></span></label>)}{fighting&&<small>战术已锁定，撤退或本场结束后可以修改。</small>}</section>
   <section className="mc-events"><h2>首领机制记录</h2><div aria-live="polite">{data.events.length?data.events.slice(-7).reverse().map((e:any,i:number)=><p key={i} className={e.kind}><time>{seconds(e.at)}</time>{e.text}</p>):<p>开战后在这里记录关键机制与处理结果。</p>}</div></section>
   <section className="mc-meter"><div className="mc-meter-tabs"><button aria-pressed={tab==='damage'} onClick={()=>setTab('damage')}>伤害</button><button aria-pressed={tab==='healing'} onClick={()=>setTab('healing')}>有效治疗</button></div>{meter.length?meter.map((m:any)=><div className="mc-meter-row" key={m.actorId}><i style={{width:(tab==='damage'?m.damage:m.healing)/max*100+'%',background:colors[m.classId]}}/><span>{m.name}</span><b>{Math.round(tab==='damage'?m.damage:m.healing).toLocaleString()}</b></div>):<p>等待第一场战斗</p>}<small>统计来自实际技能结算 · 展示前8名</small></section>
  </aside></div>
  <footer className="mc-footer"><p>独立Demo：真实职业战斗与首领机制，奖励为本次远征纪念，不进入正式角色资产。</p>{resetConfirm?<div><span>清除本机Demo的全部首领进度？</span><button disabled={busy} onClick={()=>{setResetConfirm(false);void send({type:'reset'});}}>确认重建远征</button><button onClick={()=>setResetConfirm(false)}>取消</button></div>:<button disabled={busy||fighting} onClick={()=>setResetConfirm(true)}>重建Demo远征</button>}</footer>
 </main>;
}
createRoot(document.getElementById('root')!).render(<App/>);
