import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,act,advance} from '../../../packages/game-domain/src/rules/engine.js';
import {stats,addItem,newCharacter,spellInfo} from '../../../packages/game-domain/src/rules/character.js';
import {beginDoomRitual,doomRitualUse,combatTick,startCombat} from '../../../packages/game-domain/src/rules/combat.js';
import {classEffect} from '../../../packages/game-domain/src/rules/class-mechanics.js';
const game=()=>{const s=createGame('Demon source',401,0,{classId:9,raceId:1});s.level=60;s.hp=stats(s).maxHp;s.mana=stats(s).maxMana;s.rules=[];return s;};
const helpers=s=>s.party=Array.from({length:4},(_,i)=>({...newCharacter('helper'+i,5,60,1),id:'helper'+i,hp:100,mana:100,position:0,positionY:0,rules:[]}));
test('public Inferno consumes its reagent, lands with source summon and loses initial control',()=>{let s=game();s.learned.push(1122);addItem(s,5565);s=act(s,{type:'cast',id:1122},0);assert.equal(s.activity.type,'classSpell');s=advance(s,s.activity.endsAt).state;assert.ok(!s.bag.some(i=>i.id===5565));const demon=s.combat.enemies.find(e=>e.entry===89);assert.ok(demon);assert.equal(demon.controlledBy,s.id);const until=demon.controlUntil;s.clock=until+1;combatTick(s);assert.equal(demon.controlledBy,undefined);assert.ok(demon.despawnAt>s.clock);});
test('Doom validates assistants again before payment or sacrifice on cast completion',()=>{let s=game();helpers(s);s.learned.push(18540);addItem(s,spellInfo(s,18540).Reagent1);s=act(s,{type:'cast',id:18540},0);s.party[0].hp=0;s=advance(s,s.activity.endsAt).state;assert.equal(s.combat,null);assert.ok(s.bag.some(i=>i.id===spellInfo(s,18540).Reagent1));assert.equal(s.lastDoomRitual,undefined);});
test('Doom sacrifice can kill the caster once and summons a hostile real Doomguard',()=>{const s=game();helpers(s);s.learned.push(18540);s.rngState=1;const demon=beginDoomRitual(s);assert.equal(s.lastDoomRitual.sacrifice,s.id);assert.equal(s.hp,0);assert.equal(s.totals.deaths,1);assert.equal(demon.entry,11859);assert.equal(demon.controlledBy,undefined);combatTick(s);assert.equal(s.totals.deaths,1);});
test('Enslave Demon has seeded heartbeat resistance and hostile summons despawn',()=>{const s=game();startCombat(s,[11859]);const e=s.combat.enemies[0];e.position=4;e.nextAttack=e.nextSpell=1e9;classEffect(s,s,e,spellInfo(s,11726),[s],{lands:()=>true});assert.equal(e.controlledBy,s.id);assert.ok(e.controlHeartbeatChance>0);s.rngState=1;s.clock=e.controlHeartbeatNext+1;combatTick(s);assert.equal(e.controlledBy,undefined);e.despawnAt=s.clock+1;e.nextAttack=1e9;s.clock+=100;combatTick(s);assert.ok(e.removed);});

test('Doom cancels when a required helper moves out of ritual range',()=>{let s=game();helpers(s);s.learned.push(18540);const reagent=spellInfo(s,18540).Reagent1;addItem(s,reagent);s=act(s,{type:'cast',id:18540},0);s.party[3].position=100;s=advance(s,s.activity.endsAt).state;assert.equal(s.lastDoomRitual,undefined);assert.ok(s.bag.some(i=>i.id===reagent));});
test('Doom rejects assistants in another location and rechecks location at completion',()=>{let s=game();helpers(s);s.learned.push(18540);s.party[3].location='another-location';assert.equal(doomRitualUse(s).canUse,false);s.party[3].location=s.location;const reagent=spellInfo(s,18540).Reagent1;addItem(s,reagent);s=act(s,{type:'cast',id:18540},0);assert.equal(s.activity.type,'classSpell');s.party[3].location='another-location';s=advance(s,s.activity.endsAt).state;assert.equal(s.lastDoomRitual,undefined);assert.equal(s.combat,null);assert.ok(s.bag.some(i=>i.id===reagent));});
