import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,stats} from '../../../packages/game-domain/src/rules/engine.js';
import {spells,classAbilities} from '../../../packages/game-domain/src/rules/catalog.js';
import {spellInfo} from '../../../packages/game-domain/src/rules/character.js';
import {startCombat,combatTick,hurtPlayer} from '../../../packages/game-domain/src/rules/combat.js';
import {classEffect} from '../../../packages/game-domain/src/rules/class-mechanics.js';
import {supportedSpellNames} from '../../../packages/game-domain/src/rules/class-support.js';
function setup(classId,name){const s=createGame('60 mechanic',817,0,{classId,raceId:classId===7?2:classId===11?4:classId===3?3:1});s.level=20;const id=classAbilities[classId].find(a=>spells[a.spellId]?.SpellName===name)?.spellId;assert.ok(id,`source spell ${name}`);s.learned=[id];s.rules=[{spell:id,condition:'always',value:0,enabled:true}];s.hp=stats(s).maxHp;s.mana=10000;s.rage=1000;s.energy=100;startCombat(s,[299]);const e=s.combat.enemies[0];e.hp=e.maxHp=100000;e.level=20;e.position=4;e.rootUntil=1e9;e.nextAttack=e.nextSpell=1e9;s.position=0;s.positionY=0;return{s,e,sp:spellInfo(s,id)};}
function run(s,until){for(let t=s.clock;t<=until;t+=100){s.clock=t;combatTick(s);}}
for(const name of ['Drain Life','Rain of Fire','Charge','Slice and Dice','Mana Shield','Purify','Mend Pet','Lightning Shield'])test(`${name} has executable support`,()=>assert.ok(supportedSpellNames.has(name)));
test('Drain Life channels healing and damage then stops when interrupted',()=>{const{s,e}=setup(9,'Drain Life');s.hp=100;combatTick(s);s.rules=[];run(s,2100);assert.ok(e.hp<e.maxHp);assert.ok(s.hp>100);assert.ok(s.cast?.channel);const hp=e.hp;s.stunUntil=10000;run(s,3100);assert.equal(e.hp,hp);});
test('Rain of Fire channel damages two targets at its source interval',()=>{const{s,e}=setup(9,'Rain of Fire');s.combat.enemies.push({...structuredClone(e),id:'other',position:5});combatTick(s);s.rules=[];run(s,2100);assert.ok(s.combat.enemies.every(e=>e.hp<e.maxHp));});
test('Mana Shield consumes mana in proportion to absorbed physical damage',()=>{const{s,e}=setup(8,'Mana Shield');combatTick(s);s.rules=[];const hp=s.hp,mana=s.mana;hurtPlayer(s,e,s,20);assert.equal(s.hp,hp);assert.equal(s.mana,mana-40);});
test('Slice and Dice spends combo points for a timed attack speed increase',()=>{const{s,sp}=setup(4,'Slice and Dice');s.combo=4;s.comboTarget=s.combat.enemies[0].id;combatTick(s);assert.equal(s.combo,0);assert.ok(s.auras.some(a=>a.type===138&&a.amount===20&&a.until>s.clock));});
test('Purify removes poison and disease but retains unrelated magical effects',()=>{const{s,sp}=setup(2,'Purify');s.auras=[{spell:1,effect:1,type:13,dispel:4,until:10000},{spell:2,effect:1,type:13,dispel:3,until:10000},{spell:3,effect:1,type:13,dispel:1,until:10000}];classEffect(s,s,s,sp,[s],{});assert.deepEqual(s.auras.map(a=>a.spell),[3]);});
test('Lightning Shield has finite retaliatory charges',()=>{const{s,e}=setup(7,'Lightning Shield');combatTick(s);s.rules=[];s.auras=[];s.hp=10000;for(let n=0;n<4;n++){s.clock+=3500;hurtPlayer(s,e,s,5);}assert.equal(s.logs.filter(l=>l.kind==='damage'&&l.action?.includes('Lightning Shield')).length,3);});
test('Death Coil damages its target and returns the same amount as healing',()=>{const{s,e,sp}=setup(9,'Death Coil');s.hp=10;classEffect(s,s,e,sp,[s],{damage:(s,c,t,v)=>t.hp-=v});assert.ok(e.hp<e.maxHp);assert.ok(s.hp>10);});
test('Charge energizes the warrior, never the enemy',()=>{const{s,e,sp}=setup(1,'Charge');s.rage=0;e.rage=0;classEffect(s,s,e,sp,[s],{});assert.equal(s.rage,90);assert.equal(e.rage,0);});
test('Chain Lightning damages three distinct enemies',()=>{const{s,e,sp}=setup(7,'Chain Lightning');s.combat.enemies.push({...structuredClone(e),id:'chain2',position:7},{...structuredClone(e),id:'chain3',position:10});classEffect(s,s,e,sp,[s],{lands:()=>true,damage:(s,c,t,v)=>t.hp-=v});assert.ok(s.combat.enemies.every(e=>e.hp<e.maxHp));});
test('high rank Rockbiter reads actual enchant attack power',()=>{const{s}=setup(7,'Rockbiter Weapon');const high=classAbilities[7].map(a=>spells[a.spellId]).filter(p=>p.SpellName==='Rockbiter Weapon').sort((a,b)=>b.SpellLevel-a.SpellLevel)[0];s.level=60;s.learned=[high.Id];s.rules=[{spell:high.Id,condition:'always',enabled:true}];const before=stats(s).attackPower;combatTick(s);assert.ok(Number.isFinite(stats(s).attackPower));assert.ok(stats(s).attackPower>before);});
test('Holy Shock has actual damage for enemies',()=>{const{s,e,sp}=setup(2,'Holy Shock');classEffect(s,s,e,sp,[s],{damage:(s,c,t,v)=>t.hp-=v});assert.ok(e.hp<e.maxHp);});
test('Druid Thorns still damages a melee attacker',()=>{const{s,e}=setup(11,'Thorns');combatTick(s);const hp=e.hp;hurtPlayer(s,e,s,5);assert.ok(e.hp<hp);});
test('new shields absorb only their specified school',()=>{const{s,e}=setup(8,'Fire Ward');combatTick(s);const hp=s.hp;hurtPlayer(s,e,s,10,'frost',{school:4});assert.equal(s.hp,hp-10);});
test('Blessing of Wisdom restores mana while fighting',()=>{const{s}=setup(2,'Blessing of Wisdom');s.mana=100;combatTick(s);s.rules=[];const before=s.mana;run(s,5100);assert.ok(s.mana>before);});
test('Mana Spring Totem restores nearby ally mana from its summoned aura',()=>{const{s}=setup(7,'Mana Spring Totem');s.mana=200;combatTick(s);s.rules=[];const before=s.mana;run(s,4500);assert.ok(s.mana>before);});
test('demoralizing shout applies the source attack power reduction',()=>{const{s,e,sp}=setup(1,'Demoralizing Shout');classEffect(s,s,e,sp,[s],{lands:()=>true});assert.ok(e.auras.some(a=>a.type===99&&a.amount<0));});
test('active drain channels survive JSON continuation',()=>{const{s}=setup(9,'Drain Life');s.hp=100;combatTick(s);s.rules=[];run(s,1100);const restored=structuredClone(s);run(s,5000);run(restored,5000);assert.deepEqual(restored,s);});
test('Execute converts remaining rage using source multiplier and consumes it',()=>{const{s,e,sp}=setup(1,'Execute');s.rage=300;const before=e.hp;classEffect(s,s,e,sp,[s],{damage:(s,c,t,v)=>t.hp-=v});assert.equal(s.rage,0);assert.ok(before-e.hp>sp.EffectBasePoints1+1);});
test('offhand weapons make separate attacks when Dual Wield is learned',()=>{const{s,e}=setup(4,'Sinister Strike');s.rules=[];s.learned.push(674);s.equipment[17]=structuredClone(s.equipment[16]);run(s,8000);assert.ok(s.logs.some(l=>l.kind==='damage'&&l.hand==='off'));});
test('Vampiric Embrace marks its healing source',()=>{const{s,e}=setup(5,'Shadow Word: Pain');const ve=Object.values(spells).find(p=>p.Id===15286);assert.ok(supportedSpellNames.has('Vampiric Embrace'));classEffect(s,s,e,spellInfo(s,ve.Id),[s],{});assert.equal(e.vampiricEmbrace.caster,s.id);});
test('Holy Nova heals allies and damages enemies without harming its caster',()=>{const{s,e,sp}=setup(5,'Holy Nova');s.hp=100;classEffect(s,s,e,sp,[s],{damage:(s,c,t,v)=>t.hp-=v});assert.ok(s.hp>100);assert.ok(e.hp<e.maxHp);});
test('Judgement consumes Seal of Light and creates a lasting effect',()=>{const{s,e,sp}=setup(2,'Seal of Light');classEffect(s,s,s,sp,[s],{});const judgement=spellInfo(s,20271);classEffect(s,s,e,judgement,[s],{lands:()=>true,damage:(s,c,t,v)=>t.hp-=v});assert.equal(s.seal,null);assert.ok(e.judgement?.name==='Seal of Light');});
test('Silence prevents an enemy from starting a new cast',()=>{const{s,e,sp}=setup(5,'Silence');classEffect(s,s,e,sp,[s],{lands:()=>true});assert.ok(e.silenceUntil>s.clock||e.auras.some(a=>a.type===27&&a.until>s.clock));});
test('pet command API provides persisted passive/follow/attack controls',async()=>{const effects=await import('../../../packages/game-domain/src/rules/class-spell-effects.js');assert.equal(typeof effects.petCommand,'function');const{s,e}=setup(3,'Call Pet');combatTick(s);effects.petCommand(s,{command:'passive'});assert.equal(s.pet.mode,'passive');effects.petCommand(s,{command:'attack',targetId:e.id});assert.equal(s.pet.targetId,e.id);});
test('enemy melee can critically hit',async()=>{const{enemyMeleeTick}=await import('../../../packages/game-domain/src/rules/enemy-melee.js');const{s,e}=setup(1,'Shield Block');s.position=e.position;s.hp=10000;e.nextAttack=0;const hits=[];for(let i=0;i<100;i++){s.clock=i*3000;enemyMeleeTick(s,e,s,[s],(s,e,t,v,l,d)=>hits.push(d));}assert.ok(hits.some(h=>h.critical));});
test('Flametongue imbue deals source-scaled fire damage on melee swings',()=>{const{s,e}=setup(7,'Flametongue Weapon');combatTick(s);s.rules=[];run(s,10000);assert.ok(s.logs.some(l=>l.kind==='damage'&&l.spellId===8024));});
test('summoned demons use source innate spells and keep trained spell ranks after resummon',()=>{const{s}=setup(9,'Summon Imp');s.petLearnedSkills={416:[7799]};combatTick(s);s.rules=[];run(s,13000);assert.ok(s.pet.learned.includes(7799));assert.ok(s.logs.some(l=>l.kind==='damage'&&l.spellId===7799));});
test('Consecration remains at its cast location instead of following a departing enemy',()=>{const{s,e}=setup(2,'Consecration');combatTick(s);s.rules=[];e.position=100;const hp=e.hp;run(s,3000);assert.equal(e.hp,hp);});
test('maximum rank Strength of Earth uses its own source aura',()=>{const{s}=setup(7,'Strength of Earth Totem');s.level=60;const raw=classAbilities[7].map(a=>spells[a.spellId]).filter(p=>p.SpellName==='Strength of Earth Totem').sort((a,b)=>b.SpellLevel-a.SpellLevel)[0];s.learned=[raw.Id];s.rules=[{spell:raw.Id,enabled:true,condition:'always'}];const before=stats(s).str;combatTick(s);s.rules=[];run(s,2200);assert.ok(stats(s).str-before>60);});
test('Stoneclaw Totem is a destructible threat target rather than a permanent stun',()=>{const{s,e}=setup(7,'Stoneclaw Totem');combatTick(s);s.rules=[];run(s,2200);const t=s.totems.earth;assert.ok(t.hp>0&&t.id);assert.ok(e.threat[t.id]>0);assert.notEqual(e.stunUntil,s.clock+100);});
test('Grounding Totem absorbs one magical hit and is consumed',()=>{const{s,e}=setup(7,'Grounding Totem');combatTick(s);s.rules=[];run(s,2100);const hp=s.hp;hurtPlayer(s,e,s,100,'spell',{school:2,spellId:133});assert.equal(s.hp,hp);assert.equal(s.totems.air,undefined);hurtPlayer(s,e,s,100,'spell',{school:2,spellId:133});assert.ok(s.hp<hp);});
test('Innervate benefits the selected ally rather than its caster',()=>{const{s,e,sp}=setup(11,'Innervate');const ally=structuredClone(s);ally.id='ally';classEffect(s,s,ally,sp,[s,ally],{});assert.ok(ally.innervateUntil>s.clock);assert.equal(s.innervateUntil,undefined);});
test('temporary weapon enchants bind to the selected item and do not invent charges',async()=>{const{applyClassWeaponEnchant}=await import('../../../packages/game-domain/src/rules/class-spell-effects.js');const{s}=setup(4,'Sinister Strike');s.equipment[17]={...s.equipment[16],uid:'offhand-weapon'};applyClassWeaponEnchant(s,s,spellInfo(s,8679),17);assert.equal(s.weaponEnchants[17].weaponUid,'offhand-weapon');assert.equal(s.weaponEnchants[17].charges,null);assert.equal(s.weaponEnchants[17].until,3600000);});

test('Health Funnel pays source upkeep and stops before a lethal tick',async()=>{const{classChannelTick}=await import('../../../packages/game-domain/src/rules/class-spell-effects.js');const{s,sp}=setup(9,'Health Funnel');const pet={...structuredClone(s),id:'pet',hp:1};s.hp=100;let healed=0;const api={healAmount:(s,c,t,v)=>healed+=v};classChannelTick(s,s,pet,sp,{},[s,pet],api);assert.equal(s.hp,100-sp.ManaPerSecond);assert.ok(healed>0);s.hp=sp.ManaPerSecond;s.cast={channel:true};const before=healed;classChannelTick(s,s,pet,sp,{},[s,pet],api);assert.equal(s.cast,null);assert.equal(healed,before);});

test('Viper Sting drains mana without dealing health damage',()=>{const{s,e,sp}=setup(3,'Viper Sting');s.rules=[];s.learned=[];e.mana=2000;classEffect(s,s,e,sp,[s],{lands:()=>true});const hp=e.hp;run(s,3100);assert.ok(e.mana<2000);assert.equal(e.hp,hp);});
test('dispel resistance preserves a poison when its source resists',async()=>{const{dispelClassEffects}=await import('../../../packages/game-domain/src/rules/class-spell-effects.js');const unit={dots:[{spellId:2818,dispel:4,dispelResistance:100}]};dispelClassEffects(unit,[4],1,{rngState:1});assert.equal(unit.dots.length,1);});

test('Windfury Totem gives a weapon proc without permanent attack power',()=>{const{s}=setup(7,'Windfury Totem');const ap=stats(s).attackPower;combatTick(s);s.rules=[];run(s,2200);assert.ok(s.totemWeaponEnchant?.trigger);assert.equal(stats(s).attackPower,ap);});
test('Blessing of Sacrifice transfers source damage to its caster',()=>{const{s,e,sp}=setup(2,'Blessing of Sacrifice');const ally=structuredClone(s);ally.id='ally';s.party=[ally];s.combat.participantIds.push(ally.id);classEffect(s,s,ally,sp,[s,ally],{});const own=s.hp,other=ally.hp;hurtPlayer(s,e,ally,100);assert.ok(s.hp<own);assert.ok(ally.hp>other-100);});

test('taming a real enemy channels before storing that beast as a pet',async()=>{const{beginHunterTaming}=await import('../../../packages/game-domain/src/rules/combat.js');assert.equal(typeof beginHunterTaming,'function');const{s,e}=setup(3,'Tame Beast');s.learned=[1515];e.level=1;e.nextAttack=e.nextSpell=1e9;beginHunterTaming(s,e.id);assert.ok(s.cast?.taming);assert.equal(s.pet,undefined);s.rules=[];run(s,s.cast.until+100);assert.equal(s.pet.entry,299);assert.equal(s.hunterPet.entry,299);assert.ok(e.removed);});

test('tamed beast attributes and XP use pet level instead of owner level',async()=>{const{tameClassPet,gainHunterPetXp,summonClassPet}=await import('../../../packages/game-domain/src/rules/class-spell-effects.js');const{s,e}=setup(3,'Tame Beast');s.level=60;e.level=1;tameClassPet(s,s,e,spellInfo(s,1515));assert.equal(s.pet.level,1);assert.equal(s.pet.maxHp,42);assert.equal(s.pet.armor,20);gainHunterPetXp(s,s,100);assert.equal(s.pet.level,2);assert.equal(s.pet.maxHp,55);s.pet=null;summonClassPet(s,s,spellInfo(s,883));assert.equal(s.pet.level,2);assert.equal(s.pet.maxHp,55);});
test('Flametongue Totem proc adds real fire damage',()=>{const{s}=setup(7,'Flametongue Totem');combatTick(s);s.rules=[];run(s,10000);assert.ok(s.logs.some(l=>l.kind==='damage'&&l.spellId===8253));});
test('Drain Soul death while channeling yields its source soul shard',()=>{const{s,e}=setup(9,'Drain Soul');s.rules=[{spell:1120,enabled:true,condition:'always'}];e.hp=1;combatTick(s);s.rules=[];run(s,3100);assert.ok(s.bag.some(i=>i.id===6265));});
test('Mind Control holds caster in a cancellable channel',()=>{const{s,e,sp}=setup(5,'Mind Control');classEffect(s,s,e,sp,[s],{});assert.ok(s.cast?.controlChannel);assert.equal(e.controlledBy,s.id);s.cast=null;s.rules=[];run(s,100);assert.equal(e.controlledBy,undefined);});

test('Touch of Weakness consumes its charge for source rank damage and weakness',()=>{const{s,e,sp}=setup(5,'Touch of Weakness');classEffect(s,s,s,sp,[s],{});const hp=e.hp;hurtPlayer(s,e,s,10);assert.ok(e.hp<hp);assert.equal(s.reactiveClass.charges,0);assert.ok(e.auras.some(a=>a.type===13&&a.amount<0));});
test('Shadowguard resolves its source rank trigger when struck',()=>{const{s,e,sp}=setup(5,'Shadowguard');classEffect(s,s,s,sp,[s],{});const hp=e.hp;hurtPlayer(s,e,s,10);assert.ok(e.hp<hp);});

test('Fear Ward absorbs one fear and is then consumed',async()=>{const{addCombatAura}=await import('../../../packages/sim-core/src/combat-auras.js');const{s,sp}=setup(5,'Fear Ward');classEffect(s,s,s,sp,[s],{});addCombatAura(s,{spell:5782,effect:1,type:7,mechanic:5,until:10000},0);assert.ok(!s.auras.some(a=>a.type===7));addCombatAura(s,{spell:5782,effect:1,type:7,mechanic:5,until:10000},0);assert.ok(s.auras.some(a=>a.type===7));});
