import test from 'node:test';import assert from 'node:assert/strict';
import {createGame,act} from '../../../packages/game-domain/src/rules/engine.js';
import * as character from '../../../packages/game-domain/src/rules/character.js';
import {spells,talents,table,items} from '../../../packages/game-domain/src/rules/catalog.js';
import {summonClassPet} from '../../../packages/game-domain/src/rules/class-spell-effects.js';
import {startCombat,combatTick} from '../../../packages/game-domain/src/rules/combat.js';
const make=()=>{const s=createGame('宠物属性',99,0,{classId:3,raceId:3});s.level=60;s.hp=character.stats(s).maxHp;s.hunterPet={entry:700,level:60,learned:[]};summonClassPet(s,s,character.spellInfo(s,883));return s;};
test('learned pet passive ranks add source stamina, armor and magical resistance once',()=>{const s=make(),p=s.pet,base=character.stats(p);p.learned=[4187,4188,24545,24493];const st=character.stats(p);assert.equal(st.sta,table('pet_levelstats').find(r=>r.creature_entry===1&&r.level===60).sta+5);assert.equal(st.maxHp,base.maxHp+5);assert.equal(st.armor,base.armor+50);assert.equal(st.resistances[6],30);});
test('refreshing pet caps preserves damage and death instead of healing on passive changes',()=>{const s=make(),p=s.pet;p.hp=100;const before=p.maxHp;p.learned=[4188];character.refreshPetStats(s,p);assert.equal(p.maxHp,before+5);assert.equal(p.hp,100);character.refreshPetStats(s,p);assert.equal(p.maxHp,before+5);p.hp=0;character.refreshPetStats(s,p);assert.equal(p.hp,0);});
test('pet talent changes and reset update live caps without a free heal',()=>{let s=make();s.pet.hp=100;s.location='goldshire';const endurance=Object.values(talents).find(t=>t.classId===3&&t.name==='Endurance Training');const base=s.pet.maxHp;s=act(s,{type:'talent',id:endurance.id},0);assert.equal(s.pet.maxHp,Math.floor(base*1.03));assert.equal(s.pet.hp,100);s.money=100000;s=act(s,{type:'resetTalents'},0);assert.equal(s.pet.maxHp,base);assert.equal(s.pet.hp,100);});
test('Thick Hide updates trained pet armor immediately and reset removes its multiplier',()=>{let s=make();s.location='goldshire';s.pet.hp=100;s.pet.learned=[24545];character.refreshPetStats(s,s.pet);const base=s.pet.armor,endurance=Object.values(talents).find(t=>t.classId===3&&t.name==='Endurance Training'),hide=Object.values(talents).find(t=>t.classId===3&&t.name==='Thick Hide');for(let i=0;i<5;i++)s=act(s,{type:'talent',id:endurance.id},0);s=act(s,{type:'talent',id:hide.id},0);assert.equal(s.pet.armor,base*1.1);assert.equal(character.stats(s.pet).armor,base*1.1);s.money=100000;s=act(s,{type:'resetTalents'},0);assert.equal(s.pet.armor,base);assert.equal(s.pet.hp,100);});
function hawk(rank,seed){const s=make();s.pet=null;s.learned=[75];s.rules=[];const t=Object.values(talents).find(t=>t.name==='Improved Aspect of the Hawk');s.talents={[t.id]:rank};startCombat(s,[299]);const e=s.combat.enemies[0];e.level=60;e.hp=e.maxHp=100000;e.nextAttack=e.nextSpell=e.rootUntil=1e9;s.classBuffs=[{name:'Aspect of the Hawk',spell:13165,until:1e9,stats:{rangedAttackPower:20}}];s.rngState=seed;combatTick(s);return s;}
test('Improved Hawk source rank changes chance from one to five percent while haste remains thirty percent',()=>{const missed=hawk(1,480);assert.equal(missed.hawkHasteUntil,undefined);for(const [rank,seed]of [[1,40],[5,480]]){const proc=hawk(rank,seed);assert.equal(proc.hawkHasteUntil,12000);const weapon=items[proc.equipment[18].id];assert.equal(proc.nextRanged,weapon.delay/1.3);}});
