import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,advance,view} from '../../../packages/game-domain/src/rules/engine.js';
import {spellInfo,stats} from '../../../packages/game-domain/src/rules/character.js';
import {summonClassPet,petCommand,gainHunterPetXp} from '../../../packages/game-domain/src/rules/class-spell-effects.js';
import {classEffect} from '../../../packages/game-domain/src/rules/class-mechanics.js';
const make=()=>{const s=createGame('loyalty',99,0,{classId:3,raceId:2});s.level=60;s.hp=stats(s).maxHp;s.learned.push(5149);s.hunterPet={entry:700,level:60};summonClassPet(s,s,spellInfo(s,883));return s;};
test('new hunter pets start at maximum loyalty and happiness with full training budget',()=>{const s=make();assert.equal(s.pet.loyalty,6);assert.equal(s.pet.loyaltyPoints,39500);assert.equal(s.pet.happiness,1000000);assert.equal(s.pet.trainingPoints,300);assert.equal(s.pet.loyaltyXpRemaining,0);});
test('elapsed time and combat experience do not reduce or change loyalty and happiness',()=>{let s=make();s=advance(s,1800000).state;assert.equal(s.pet.loyalty,6);assert.equal(s.pet.happiness,1000000);const points=s.pet.trainingPoints;gainHunterPetXp(s,s,1000000);assert.equal(s.pet.loyalty,6);assert.equal(s.pet.happiness,1000000);assert.equal(s.pet.trainingPoints,points);});
test('older active pet state is raised to full loyalty without losing training progress',()=>{let s=make();s.pet.loyalty=2;s.pet.loyaltyPoints=10;s.pet.trainingPoints=60;s.pet.happiness=0;const full=advance(s,24000).state;const part=advance(JSON.parse(JSON.stringify(advance(s,9000).state)),24000).state;assert.equal(full.pet.loyalty,6);assert.equal(full.pet.happiness,1000000);assert.equal(full.pet.trainingPoints,300);assert.deepEqual(full.pet,part.pet);});
test('dismissed and stabled pets are raised to full values even without elapsed time',()=>{let s=make();s.pet=null;s.hunterPet={entry:700,level:60,loyalty:2,happiness:0,trainingPoints:20};s.stablePets=[{entry:299,level:40,loyalty:1,happiness:0,trainingPoints:0}];s=advance(s,0).state;assert.equal(s.hunterPet.loyalty,6);assert.equal(s.hunterPet.happiness,1000000);assert.equal(s.hunterPet.trainingPoints,260);assert.equal(s.stablePets[0].loyalty,6);assert.equal(s.stablePets[0].trainingPoints,200);});
test('feeding remains available in pet controls while happiness stays full',()=>{let s=make();s.learned.push(6991);s.bag=[{uid:'food',id:8952,count:2},{uid:'bread',id:414,count:1}];assert.deepEqual(view(s).petControls.food.map(food=>food.id),[8952]);assert.throws(()=>petCommand(s,{command:'feed',itemId:414}),/不适合/);petCommand(s,{command:'feed',itemId:8952});assert.equal(s.bag[0].count,1);assert.ok(s.pet.feeding);assert.throws(()=>petCommand(s,{command:'feed',itemId:8952}),/正在进食/);s=advance(s,20000).state;assert.equal(s.pet.feeding,null);assert.equal(s.pet.happiness,1000000);assert.equal(s.pet.loyalty,6);});
test('pet training limits four distinct active chains while allowing upgrades and passive skills',()=>{const s=make(),p=s.pet;p.trainingPoints=300;p.learned=[2649,17253,16827,23099];p.availableSkills=[24450,17255,4187];const before=JSON.stringify(p);assert.throws(()=>petCommand(s,{command:'train',spellId:24450}),/four|4|四/);assert.equal(JSON.stringify(p),before);petCommand(s,{command:'train',spellId:17255});assert.ok(p.learned.includes(17255));petCommand(s,{command:'train',spellId:4187});assert.ok(p.learned.includes(4187));});
test('training rejects family-incompatible, dead, combat and unaffordable skills without spending',()=>{const s=make(),p=s.pet;p.trainingPoints=300;p.availableSkills=[7371,24450];assert.throws(()=>petCommand(s,{command:'train',spellId:7371}),/family|家族/);p.hp=0;assert.throws(()=>petCommand(s,{command:'train',spellId:24450}));p.hp=100;s.combat={};assert.throws(()=>petCommand(s,{command:'train',spellId:24450}));s.combat=null;p.trainingPoints=0;assert.throws(()=>petCommand(s,{command:'train',spellId:24450}),/points|训练/);assert.equal(p.trainingPoints,0);});
test('dismiss and recall preserve spent training points and learned skills at full loyalty',()=>{const s=make();s.pet.trainingPoints=29;s.pet.learned=[2649];classEffect(s,s,s,spellInfo(s,2641),[s],{});assert.equal(s.pet,null);s.clock=60000;summonClassPet(s,s,spellInfo(s,883));assert.equal(s.pet.loyalty,6);assert.equal(s.pet.happiness,1000000);assert.equal(s.pet.trainingPoints,29);assert.ok(s.pet.learned.includes(2649));});

test('rank upgrades charge only the additional source points and downgrades cannot refund them',()=>{const s=make(),p=s.pet;p.trainingPoints=20;p.learned=[17253];p.availableSkills=[17255];petCommand(s,{command:'train',spellId:17255});assert.equal(p.trainingPoints,17);const before=p.trainingPoints;p.learned=[17255];p.availableSkills.push(17253);assert.throws(()=>petCommand(s,{command:'train',spellId:17253}),/更高/);assert.equal(p.trainingPoints,before);});
test('pet level-ups still award five training points at fixed full loyalty',()=>{const s=make();s.pet.level=59;s.pet.trainingPoints=100;gainHunterPetXp(s,s,1000000);assert.equal(s.pet.level,60);assert.equal(s.pet.trainingPoints,105);});
