import test from 'node:test';
import assert from 'node:assert/strict';
import {createGame,stats} from '../../../packages/game-domain/src/rules/engine.js';
import {enemy} from '../../../packages/game-domain/src/rules/character.js';
import {spells,table} from '../../../packages/game-domain/src/rules/catalog.js';
import {enemyAITick} from '../../../packages/game-domain/src/rules/enemy-ai.js';
import {castEnemySpell,enemySpellInfo} from '../../../packages/game-domain/src/rules/enemy-spells.js';
function fixture(entry=1663){const s=createGame('技能验证',812,0);s.hp=stats(s).maxHp;s.position=0;s.positionY=0;const e=enemy(s,entry,'enemy');e.level=60;e.position=2;e.positionY=0;e.target=s.id;s.combat={id:'stock-spells',enemies:[e],projectiles:[]};return{s,e};}
const hurt=(hits)=>(s,e,t,damage,name,detail)=>hits.push({target:t.id,damage,...detail});
test('Stockades Strike uses weapon damage effect17',()=>{const{s,e}=fixture(),hits=[];assert.equal(castEnemySpell(s,e,s,11976,[s],hurt(hits),2),true);assert.ok(hits.length&&hits[0].damage>0);});
test('Stockades Kick interrupts an active cast and locks only its school',()=>{const{s,e}=fixture(1706);s.cast={spell:133,until:10000};castEnemySpell(s,e,s,1766,[s],()=>{},2);assert.equal(s.cast,null);assert.ok(s.schoolLockouts[spells[133].School]>s.clock);assert.equal(s.schoolLockouts[6],undefined);});
test('Dextren fear triggers its primary target stun',()=>{const{s,e}=fixture();castEnemySpell(s,e,s,19134,[s],()=>{},2);assert.ok(s.auras.some(a=>a.spell===29544&&a.type===12));});
test('Hamhock Chain Lightning jumps to three nearby unique targets with falloff',()=>{const{s,e}=fixture(1717),hits=[];const actors=[s,...[1,2,3].map(n=>({...structuredClone(s),id:'ally'+n,position:n*3}))];castEnemySpell(s,e,s,421,actors,hurt(hits),2);assert.equal(hits.length,3);assert.equal(new Set(hits.map(h=>h.target)).size,3);assert.ok(hits[0].damage>hits[1].damage&&hits[1].damage>hits[2].damage);});
function isolateEvent(s,e,id){e.ai={phase:0,lastAt:0,nextCheck:0,events:Object.fromEntries(table('creature_ai_scripts').filter(r=>r.creature_id===e.entry).map(r=>[r.id,{remaining:0,done:r.id!==id}]))};s.clock=1000;}
test('Kam range event9 casts Shield Slam only within its source range',()=>{for(const range of [3,10]){const{s,e}=fixture(1666),hits=[];e.position=range;isolateEvent(s,e,166603);enemyAITick(s,e,[s],hurt(hits));assert.equal(hits.some(h=>h.spellId===8242),range===3);}});
test('Captive event33 uses target facing instead of firing Backstab from the front',()=>{for(const behind of [false,true]){const{s,e}=fixture(1707),hits=[];const facing=enemy(s,1711,'facing');facing.position=10;facing.positionY=0;s.combat.enemies.push(facing);s.target=facing.id;e.position=behind?-2:2;isolateEvent(s,e,170701);enemyAITick(s,e,[s],hurt(hits));assert.equal(hits.some(h=>h.spellId===7159),behind);}});
test('NPC stances apply source passive effects and replace the prior stance',()=>{const{s,e}=fixture(1666);castEnemySpell(s,e,e,7164,[s],()=>{},2);assert.deepEqual(e.auras.filter(a=>a.spell===7376).map(a=>[a.type,a.amount]),[[87,-10],[79,-10],[10,30]]);castEnemySpell(s,e,e,7165,[s],()=>{},2);assert.ok(!e.auras.some(a=>[7164,7376].includes(a.spell)));assert.ok(e.auras.some(a=>a.spell===21156&&a.type===10&&a.amount===-20));});
test('enemy direct spell damage honors school-matched damage percent auras',()=>{const cast=modified=>{const{s,e}=fixture(),hits=[];if(modified)e.auras=[{type:79,amount:-10,misc:1,until:10000}];castEnemySpell(s,e,s,1766,[s],hurt(hits),2);return hits[0].damage;};assert.equal(cast(true),cast(false)*.9);});
test('NPC Kick with no energy pool executes through ordinary AI timers',()=>{const{s,e}=fixture(1706);s.cast={spell:133,until:10000};isolateEvent(s,e,170601);enemyAITick(s,e,[s],()=>{});assert.equal(s.cast,null);assert.equal(e.mana,0);assert.ok(e.ai.events[170601].remaining>=10400);});
test('NPC Rend with no rage pool executes normally without changing player spell cost',()=>{const{s,e}=fixture(1708);isolateEvent(s,e,170802);enemyAITick(s,e,[s],()=>{});assert.ok(s.auras?.some(a=>a.spell===6547&&a.type===3));assert.equal(e.mana,0);assert.equal(enemySpellInfo({...e,classId:1},6547).mana,100);});
