import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {PGlite} from '@electric-sql/pglite';
import {AccountStore} from '../src/account-store.ts';
import {AdminStore} from '../src/admin-store.ts';
import {createGameServer} from '../src/server.ts';
import {PostgresStore} from '../../../packages/persistence/src/postgres.ts';
import {GameService} from '../../../packages/game-domain/src/service.ts';
import {GmService} from '../../../packages/game-domain/src/gm.ts';
import {CONTENT_VERSION} from '../../../packages/game-domain/src/rules/client-content.js';

test('real SQL and HTTP: GM-only dispatch, owner-only claim, audit rollback and expired buffs bypass old ETags',async t=>{
 const db=new PGlite();let tail=Promise.resolve(),now=1000000;
 const pool={async connect(){const previous=tail;let release!:()=>void;tail=new Promise<void>(resolve=>{release=resolve;});await previous;return {query:async(text:string,values?:any[])=>text.includes('CREATE TABLE')?(await db.exec(text),{rows:[]}):db.query(text,values),release};},end:()=>db.close()};
 const sql={query:async(text:string,values?:any[])=>{const client=await pool.connect();try{return await client.query(text,values);}finally{client.release();}}};
 const store=new PostgresStore(pool);await store.initialize();
 const accounts=new AccountStore(sql,()=>now);await accounts.initialize();const admin=new AdminStore(sql,accounts,()=>now);await admin.initialize();
 const service=new GameService(store,{contentVersion:CONTENT_VERSION,now:()=>now}),gm=new GmService(store,()=>now);
 const user=await accounts.register('recipient','recipient-password'),other=await accounts.register('other-player','another-password');
 const save=await service.createSave(user.user.id,{name:'收件人',classId:8,raceId:1},'first-save');
 const management=await admin.authenticate('register',{username:'gm-admin',password:'management-password'},'test');
 const origin='http://game.test';const game=createGameServer({service,gm,admin,accounts,appOrigin:origin,trustProxyHops:0});game.server.listen(0,'127.0.0.1');await once(game.server,'listening');t.after(async()=>{await game.close();await store.close();});
 const base=`http://127.0.0.1:${(game.server.address() as {port:number}).port}`;
 const userHeaders={cookie:`wow_session=${user.token}`,origin,'content-type':'application/json'},adminHeaders={cookie:`wow_admin=${management.token}`,origin,'content-type':'application/json'};
 const post=(path:string,body:unknown,headers=adminHeaders)=>fetch(base+path,{method:'POST',headers,body:JSON.stringify(body)});
 const query=`?saveId=${encodeURIComponent(save.id)}`;
 assert.equal((await fetch(base+'/api/admin/gm',{headers:userHeaders})).status,401);
 assert.equal((await fetch(base+'/api/admin/gm-items?search=2589',{headers:userHeaders})).status,401);
 const definition={action:'saveGift',name:'测试礼包',description:'事务奖励',copper:20000,items:[{id:2589,count:4},{id:49283,count:1}],reason:'API 测试',requestId:'template-create'};
 assert.equal((await post('/api/admin/gm',definition,{...adminHeaders,origin:'http://foreign.test'})).status,403);
 const template=await (await post('/api/admin/gm',definition)).json();assert.ok(template.id);
 const dispatch={action:'sendGift',templateId:template.id,scope:'player',userId:user.user.id,reason:'发放测试',requestId:'dispatch-001'};
 assert.equal((await post('/api/admin/gm',{...dispatch,userId:'not-a-user'})).status,400);
 const [first,retry]=await Promise.all([post('/api/admin/gm',dispatch),post('/api/admin/gm',dispatch)]);assert.equal(first.status,200);assert.deepEqual(await first.json(),await retry.json());
 const inbox=await (await fetch(base+'/api/game/mail'+query,{headers:userHeaders})).json();assert.equal(inbox.mail.length,1);
 assert.equal((await fetch(base+'/api/game/mail'+query,{headers:{cookie:`wow_session=${other.token}`}})).status,404);
 const claimed=await post('/api/game'+query,{type:'claimMail',id:inbox.mail[0].id,requestId:'claim-gift-001'},userHeaders);assert.equal(claimed.status,200);const player=(await claimed.json()).snapshot.player;assert.equal(player.money,20000);assert.ok(player.bag.some((item:any)=>item.id===49283));assert.deepEqual(player.mounts,[]);
 const learn=await post('/api/game'+query,{type:'useItem',uid:player.bag.find((item:any)=>item.id===49283).uid,requestId:'learn-tiger-001'},userHeaders);assert.equal(learn.status,200);assert.deepEqual((await learn.json()).snapshot.player.mounts,[49283]);
 assert.equal((await service.mailInbox(save.id)).length,0);
 // Inject an audit failure: no delivery or account revision may escape the transaction.
 const revision=(await service.snapshot(save.id)).revision;
 await sql.query(`CREATE FUNCTION reject_gm_operation() RETURNS trigger AS $$ BEGIN RAISE EXCEPTION 'audit unavailable'; END; $$ LANGUAGE plpgsql`);
 await sql.query('CREATE TRIGGER reject_gm_operation BEFORE INSERT ON gm_operations FOR EACH ROW EXECUTE FUNCTION reject_gm_operation()');
 assert.equal((await post('/api/admin/gm',{...dispatch,requestId:'dispatch-failed'})).status,503);
 assert.equal((await service.mailInbox(save.id)).length,0);assert.equal((await service.snapshot(save.id)).revision,revision);
 await sql.query('DROP TRIGGER reject_gm_operation ON gm_operations');
 assert.equal((await post('/api/admin/gm',{action:'issueBuff',scope:'all',name:'到期测试',description:'真实时间到期',durationMinutes:1,effects:{maxHp:100},reason:'过期测试',requestId:'buff-expiration'})).status,200);
 const before=await fetch(base+'/api/game'+query,{headers:userHeaders}),etag=before.headers.get('etag')!;assert.ok((await before.json()).snapshot.player.serverBuffs.some((buff:any)=>buff.gm));
 now+=61000;const after=await fetch(base+'/api/game'+query,{headers:{...userHeaders,'if-none-match':etag}});assert.equal(after.status,200);assert.ok(!(await after.json()).snapshot.player.serverBuffs.some((buff:any)=>buff.gm));
 const audit=await (await fetch(base+'/api/admin/audit?search=sendGift',{headers:adminHeaders})).json();assert.equal(audit.rows.length,1);
});
