import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {randomBytes} from 'node:crypto';
import {MemoryStore} from '../../../packages/persistence/src/memory.ts';
import {SimulationRepository} from '../../../packages/persistence/src/simulation.ts';
import {residentStore} from '../../../packages/game-domain/src/resident-store.ts';
import {ResidentCharacters} from '../../../packages/game-domain/src/resident-characters.ts';
import {GameService} from '../../../packages/game-domain/src/service.ts';
import {GmService} from '../../../packages/game-domain/src/gm.ts';
import {runtimeVersion} from '../../simulation-host/src/version.ts';
import {SimulationDirectory} from '../../simulation-host/src/directory.ts';
import {createSimulationServer} from '../../simulation-host/src/server.ts';
import {SimulationClient} from '../src/simulation-client.ts';
import {ResidentGameService} from '../src/resident-game-service.ts';
import {createGameServer} from '../src/server.ts';
import {accounts,issueSession,appOrigin} from './session-fixture.ts';


test('authenticated HTTP uses resident authority, rejects stale input, and never accepts client state',async t=>{
 const store=residentStore(new MemoryStore()),domain=new GameService(store,{contentVersion:runtimeVersion.contentHash,seed:()=>283});
 await domain.createAccount('account-a',{name:'服务器法师',classId:8,raceId:1},'create');
 const characters=new ResidentCharacters(store,{version:runtimeVersion});
 const directory=new SimulationDirectory(new SimulationRepository(store,Date.now,characters.commit),{characters,workers:1});
 const token=randomBytes(32).toString('base64url');
 const simulation=createSimulationServer(directory,{token});simulation.server.listen(0,'127.0.0.1');await once(simulation.server,'listening');
 t.after(()=>simulation.close());
 const client=new SimulationClient({url:`http://127.0.0.1:${(simulation.server.address() as any).port}`,token});
 const service=new ResidentGameService(domain,client);
 const game=createGameServer({service,accounts,appOrigin});game.server.listen(0,'127.0.0.1');await once(game.server,'listening');t.after(()=>game.close());
 const origin=`http://127.0.0.1:${(game.server.address() as any).port}`;
 const headers={origin:appOrigin,cookie:`wow_session=${await issueSession({sub:'account-a'})}`,'content-type':'application/json'};
 const read=async()=>{const response=await fetch(origin+'/api/game',{headers});assert.equal(response.status,200);return response.json() as Promise<any>;};
 const post=(body:any)=>fetch(origin+'/api/game',{method:'POST',headers,body:JSON.stringify(body)});
 let current=await read();assert.ok(current.execution);assert.equal(current.combatMode,'realtime');assert.equal(Object.hasOwn(current,'localSimulation'),false);
 const {instanceId,controllerGeneration,clientSequence}=current.execution;
 const input={type:'settings',autoLoot:true,requestId:'settings',execution:{instanceId,controllerGeneration,clientSequence:clientSequence+1}};
 assert.equal((await post(input)).status,200);
 assert.equal((await post(input)).status,200,'request retry is idempotent');
 assert.equal((await post({...input,autoLoot:false})).status,409,'request identity cannot change meaning');
 current=await read();assert.equal(current.snapshot.player.settings.autoLoot,true);
 const gm=new GmService(store);
 const gift=await gm.execute('admin',{action:'saveGift',name:'测试礼包',description:'服务器领取',copper:50000,items:[{id:2589,count:3}],reason:'领取回归测试',requestId:'resident-gift-template'});
 await gm.execute('admin',{action:'sendGift',templateId:gift.id,scope:'all',reason:'领取回归测试',requestId:'resident-gift-delivery'});
 const inbox=await fetch(origin+'/api/game/mail',{headers});assert.equal(inbox.status,200);
 const delivery=(await inbox.json()).mail[0];assert.ok(delivery?.id);
 current=await read();
 const giftOwner=current.execution;
 const claimInput={type:'claimMail',id:delivery.id,requestId:'resident-gift-claim',execution:{instanceId:giftOwner.instanceId,controllerGeneration:giftOwner.controllerGeneration,clientSequence:giftOwner.clientSequence+1}};
 const claim=await post(claimInput);
 assert.equal(claim.status,200,JSON.stringify(await claim.clone().json()));
 assert.equal((await post(claimInput)).status,200,'retrying the same claim is idempotent');
 const giftDeadline=Date.now()+10000;
 do{current=await read();if(current.snapshot.player.money===50000)break;await delay(50);}while(Date.now()<giftDeadline);
 assert.equal(current.snapshot.player.money,50000);
 assert.ok(current.snapshot.player.bag.some((item:any)=>item.id===2589));
 assert.equal((await (await fetch(origin+'/api/game/mail',{headers})).json()).mail.length,0);
 await domain.createAccount('account-b',{name:'收信战士',classId:1,raceId:1},'create-recipient');
 const sentItem=current.snapshot.player.bag.find((item:any)=>item.id===2589);
 const sendOwner=current.execution;
 const sendInput={type:'sendMail',recipient:'收信战士',subject:'测试邮件',body:'即时送达',copper:10000,items:[{uid:sentItem.uid,count:2}],requestId:'resident-send-mail',execution:{instanceId:sendOwner.instanceId,controllerGeneration:sendOwner.controllerGeneration,clientSequence:sendOwner.clientSequence+1}};
 const mailed=await post(sendInput);
 assert.equal(mailed.status,200,JSON.stringify(await mailed.clone().json()));
 assert.equal((await post(sendInput)).status,200,'retrying the same mail does not charge twice');
 current=await read();assert.equal(current.snapshot.player.money,40000);
 assert.equal(current.snapshot.player.bag.find((item:any)=>item.uid===sentItem.uid)?.count,1);
 const recipientHeaders={...headers,cookie:`wow_session=${await issueSession({sub:'account-b'})}`};
 const recipientInbox=await fetch(origin+'/api/game/mail',{headers:recipientHeaders});assert.equal(recipientInbox.status,200);
 const received=(await recipientInbox.json()).mail;assert.equal(received.length,1);assert.equal(received[0].subject,'测试邮件');
 const recipientSnapshot=await (await fetch(origin+'/api/game',{headers:recipientHeaders})).json();
 const receiveOwner=recipientSnapshot.execution;
 const receive=await fetch(origin+'/api/game',{method:'POST',headers:recipientHeaders,body:JSON.stringify({type:'claimMail',id:received[0].id,requestId:'resident-receive-mail',execution:{instanceId:receiveOwner.instanceId,controllerGeneration:receiveOwner.controllerGeneration,clientSequence:receiveOwner.clientSequence+1}})});
 assert.equal(receive.status,200,JSON.stringify(await receive.clone().json()));
 const recipientAfter=await (await fetch(origin+'/api/game',{headers:recipientHeaders})).json();
 assert.equal(recipientAfter.snapshot.player.money,10000);
 assert.ok(recipientAfter.snapshot.player.bag.some((item:any)=>item.id===2589&&item.count===2));
 assert.equal((await (await fetch(origin+'/api/game/mail',{headers:recipientHeaders})).json()).mail.length,0);
 const before=current.snapshot.player.money;
 const removed=await fetch(origin+'/api/game/local',{method:'POST',headers,body:JSON.stringify({type:'checkpoint',requestId:'forged',state:{money:99999999}})});
 assert.equal(removed.status,404);
 current=await read();assert.equal(current.snapshot.player.money,before);
 const owner=current.execution;
 assert.equal((await post({type:'hunt',id:299,requestId:'hunt-0001',execution:{instanceId:owner.instanceId,controllerGeneration:owner.controllerGeneration,clientSequence:owner.clientSequence+1}})).status,200);
 const deadline=Date.now()+10000;
 do{await delay(100);current=await read();}while(!current.snapshot.player.combat&&Date.now()<deadline);
 assert.ok(current.snapshot.player.combat,'owner advances hunting without a browser engine');
 assert.equal(Object.hasOwn(current.snapshot.player,'rngState'),false);
});

test('remote version failures retain a terminal code and server diagnostics, while transient failures can retry',async t=>{
 const store=new MemoryStore(),domain=new GameService(store,{contentVersion:runtimeVersion.contentHash});
 t.after(()=>store.close());
 const actor=(await domain.createAccount('load-failure',{name:'恢复诊断',classId:8,raceId:1},'create')).state;
 const logs:unknown[][]=[];t.mock.method(console,'error',(...args:unknown[])=>logs.push(args));
 let attempts=0;
 let failure=Object.assign(new Error('internal shared runtime details'),{code:'SIMULATION_VERSION',status:503});
 const simulation={openCharacter:async()=>{attempts++;throw failure;}} as unknown as SimulationClient;
 const service=new ResidentGameService(domain,simulation);
 await assert.rejects(service.snapshot('load-failure'),(e:any)=>e.code==='SIMULATION_VERSION'&&e.status===409&&!e.message.includes('internal'));
 failure=Object.assign(new Error('temporary ownership fence'),{code:'SIMULATION_FENCED',status:503});
 await assert.rejects(service.snapshot('load-failure'),(e:any)=>e.code==='SIMULATION_UNAVAILABLE'&&e.status===503);
 assert.equal(attempts,2,'the failed route is discarded before retry');
 assert.deepEqual(logs[0],['Resident snapshot failed',{accountId:'load-failure',actorId:actor.id,code:'SIMULATION_VERSION',status:503,message:'internal shared runtime details'}]);
});
