import test from 'node:test';
import assert from 'node:assert/strict';
import {once} from 'node:events';
import {setTimeout as delay} from 'node:timers/promises';
import {randomBytes} from 'node:crypto';
import {MemoryStore} from '../../../packages/persistence/src/memory.ts';
import {SimulationRepository} from '../../../packages/persistence/src/simulation.ts';
import {residentStore} from '../../../packages/game-domain/src/resident-store.ts';
import {ResidentCharacters} from '../../../packages/game-domain/src/resident-characters.ts';
import {GameService} from '../../../packages/game-domain/src/service.ts';
import {runtimeVersion} from '../../simulation-host/src/version.ts';
import {SimulationDirectory} from '../../simulation-host/src/directory.ts';
import {createSimulationServer} from '../../simulation-host/src/server.ts';
import {SimulationClient} from '../src/simulation-client.ts';
import {ResidentGameService} from '../src/resident-game-service.ts';
import {createGameServer} from '../src/server.ts';
import {accounts,issueSession,appOrigin} from './session-fixture.ts';


test('authenticated HTTP uses resident authority, rejects stale input, and never accepts client state',async t=>{
 const store=residentStore(new MemoryStore()),domain=new GameService(store,{contentVersion:runtimeVersion.contentHash,seed:()=>283});
 await domain.createAccount('account-a',{name:'服务器法师',classId:8,raceId:1},'create');
 const characters=new ResidentCharacters(store,{version:runtimeVersion});
 const directory=new SimulationDirectory(new SimulationRepository(store,Date.now,characters.commit),{characters,workers:1});
 const token=randomBytes(32).toString('base64url');
 const simulation=createSimulationServer(directory,{token});simulation.server.listen(0,'127.0.0.1');await once(simulation.server,'listening');
 t.after(()=>simulation.close());
 const client=new SimulationClient({url:`http://127.0.0.1:${(simulation.server.address() as any).port}`,token});
 const service=new ResidentGameService(domain,client);
 const game=createGameServer({service,accounts,appOrigin});game.server.listen(0,'127.0.0.1');await once(game.server,'listening');t.after(()=>game.close());
 const origin=`http://127.0.0.1:${(game.server.address() as any).port}`;
 const headers={origin:appOrigin,cookie:`wow_session=${await issueSession({sub:'account-a'})}`,'content-type':'application/json'};
 const read=async()=>{const response=await fetch(origin+'/api/game',{headers});assert.equal(response.status,200);return response.json() as Promise<any>;};
 const post=(body:any)=>fetch(origin+'/api/game',{method:'POST',headers,body:JSON.stringify(body)});
 let current=await read();assert.ok(current.execution);assert.equal(current.combatMode,'realtime');assert.equal(Object.hasOwn(current,'localSimulation'),false);
 const {instanceId,controllerGeneration,clientSequence}=current.execution;
 const input={type:'settings',autoLoot:true,requestId:'settings',execution:{instanceId,controllerGeneration,clientSequence:clientSequence+1}};
 assert.equal((await post(input)).status,200);
 assert.equal((await post(input)).status,200,'request retry is idempotent');
 assert.equal((await post({...input,autoLoot:false})).status,409,'request identity cannot change meaning');
 current=await read();assert.equal(current.snapshot.player.settings.autoLoot,true);
 const before=current.snapshot.player.money;
 const removed=await fetch(origin+'/api/game/local',{method:'POST',headers,body:JSON.stringify({type:'checkpoint',requestId:'forged',state:{money:99999999}})});
 assert.equal(removed.status,404);
 current=await read();assert.equal(current.snapshot.player.money,before);
 const owner=current.execution;
 assert.equal((await post({type:'hunt',id:299,requestId:'hunt-0001',execution:{instanceId:owner.instanceId,controllerGeneration:owner.controllerGeneration,clientSequence:owner.clientSequence+1}})).status,200);
 const deadline=Date.now()+10000;
 do{await delay(100);current=await read();}while(!current.snapshot.player.combat&&Date.now()<deadline);
 assert.ok(current.snapshot.player.combat,'owner advances hunting without a browser engine');
 assert.equal(Object.hasOwn(current.snapshot.player,'rngState'),false);
});
